### ISSUE TITLE
When installer fails

### ISSUE THREAD

**Issue by chrissie1** [chocolatey/chocolatey#10]
When an installer fails to install the package should not be put in the lib folder or be removed from the lib folder.

**Comment by mkmurray** [comment]
Yeah I just ran into this, I don't think it's fully fixed.

**Comment by ferventcoder** [comment]
@mkmurray let's chat on chocolatey/choco, ensure you are on 0.9.10.x.

**Comment by ferventcoder** [comment]
What you are seeing is likely a different issue and definitely not over here on the old POSH version. Https://github.com/chocolatey/choco/issues/new
