### ISSUE TITLE
Package Request: Paint.Net

### ISSUE THREAD

**Issue by staxmanade** [chocolatey/chocolatey#12]
I found some documentation on the silent install options. (Haven't tried it) http://eecs.wsu.edu/paint.net/doc/2.6/Help/en/UnattendedInstallation.html

**Comment by zilexa** [comment]
I have tried lots of options to get this to work:
call C:\ProgramData\chocolatey\choco install paint.net -installargs 'JPGPNGBMPEDITOR=1 TGAEDITOR=1 DESKTOPSHORTCUT=0 CHECKFORUPDATES=0'

But whatever I do, choco thinks the arguments are packages, as if I want to install multiple packages. I played with single and double quotes and eventually at some point managed to get the first argument to be an actual argument, but all the others are still considered packages.

**Comment by gep13** [comment]
@zilexa have a look here:

https://github.com/chocolatey/choco/wiki/CommandsReference#how-to-pass-options--switches

Hopefully that will help.

**Comment by ferventcoder** [comment]
@zilexa also that menu is there when you type `choco install -h`
