### ISSUE TITLE
Chocolatey install did not configure $env:Path

### ISSUE THREAD

**Issue by dotnetchris** [chocolatey/chocolatey#140]
After installing Chocolatey by executing the @powershell.... command on the chocolatey.org homepage, my environment path was not updated. 

After the install: 

C:\projects> Get-Command chocolatey
Get-Command : The term 'chocolatey' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.

With my hacking:

C:\projects> $env:Path += ";C:\Chocolatey\bin\;"

C:\projects> Get-Command chocolatey

CommandType     Name                                                                     Definition
Application     chocolatey.bat                                                           C:\Chocolatey\bin\chocolatey.bat

Windows 7 Pro x64
Powershell policy unrestricted
UAC disabled

**Comment by ferventcoder** [comment]
Just FYI - choco 0.9.10 supports this now without closing and reopening your shell - https://github.com/chocolatey/choco/issues/664

**Comment by acgetchell** [comment]
After running
```powershell
choco install cmake.install --installargs 'ADD_CMAKE_TO_PATH=""System""'
refreshenv
```
I still have to close out the Admin PowerShell window before ```cmake``` is found.

Same thing happens with:
```
choco install git -y
refreshenv
```

**Comment by ferventcoder** [comment]
@acgetchell Can you tell me the output of calling refreshenv? Does it say "Refreshing for ***cmd.exe***" or does it say for ***powershell.exe***?  If it says the former, it means you do not have the PowerShell profile installed - which provides this and tab completion.

See https://chocolatey.org/docs/troubleshooting#why-does-choco-intab-not-work-for-me on how to remedy this so that when you call refreshenv, it is the PowerShell version that is being called and not refreshenv.bat.

**Comment by ferventcoder** [comment]
Please see https://github.com/chocolatey/choco/issues/991 and https://github.com/chocolatey/choco/issues/894 to get a better understanding of why this isn't set by default on install.

**Comment by ferventcoder** [comment]
I also filed https://github.com/chocolatey/choco/issues/1392

**Comment by acgetchell** [comment]
Works now. 👍 💯 

![screen shot 2017-08-27 at 11 19 20 am](https://user-images.githubusercontent.com/434849/29752814-cbded11e-8b19-11e7-815a-2d2068dc5155.png)

**Comment by ferventcoder** [comment]
@acgetchell Looks like an artifact of already having that in the PATH when you ran it the second time. It doesn't show that environment variables like PATH were updated in the output and I don't see a call to refreshenv here.
