### ISSUE TITLE
[Enhancement] Create shell redirects

### ISSUE THREAD

**Issue by Mathnerd314** [chocolatey/chocolatey#148]
MSYS doesn't pick up batch files as executable, so you have to run them with cmd //c \<prog\>. This is pretty easy to work around with a shell script named \<prog\> (no extension):
```bash
#!/bin/sh
cmd //c <prog.cmd> "$@"
```

Alternately, you could just remove the redirects and add the executable-containing folders to the path directly. I think I'd prefer that, honestly.

**Comment by ferventcoder** [comment]
Shimgen has fixed this.
