### ISSUE TITLE
[Install-ChocolateyPath] Should create user PATH as REG_EXPAND_SZ

### ISSUE THREAD

**Issue by FunkMonkey** [chocolatey/chocolatey#156]
If the path variable does not exist, the ChocolateyPath helper has to create the PATH user environment variable as [REG_EXPAND_SZ](http://msdn.microsoft.com/en-us/library/windows/desktop/ms724884%28v=vs.85%29.aspx) instead of REG_SZ, otherwise other environment variables that are used in the PATH string will not be expanded.

If anyone adds something to the PATH that contains an environment variable like %SystemRoot%, this variable will not be expanded to f. ex. "C:\Windows" and commands/executables that rely on this behaviour will not be found. This can happen for everyone who adds something to PATH, not only package owners, but also completely seperate applications that have no knowledge of Chocolatey.

Instructions on how to save PATH as REG_EXPAND_SZ can be found [here](http://stackoverflow.com/questions/11294318/setting-environemnt-type-to-reg-expand-sz-using-powershell)

**Comment by ferventcoder** [comment]
Fixed by https://github.com/chocolatey/choco/issues/699
