### ISSUE TITLE
[Enhancement] Extra metadata in nuspec for package source url

### ISSUE THREAD

**Issue by Iristyle** [chocolatey/chocolatey#172]
Chocolatey is a little different from Nuget.  

* With NuGet packages, the publisher is usually the author.
* With Chocolatey, most times the guy putting together the package is not the author.  The 'Project Site' in the gallery / `projectUrl` in the nuspec typically points back to the authors project, not the publishers...

When looking in the directory, it can be nice to have a convenient way to get back to the author.

* Maybe you want to look at `install.ps1` to see what it does before you try installing it
* Maybe they pulled off some really interesting trick in `install.ps1` (that as a pkg author you'd like to see) -- wacky switches for silent installs to an obscure installer, etc
* Maybe you've found a bug and want to notify the author through GitHub / submit a pull req
* Maybe the thing is so large that you don't want to `cinst` the package to get at any of these details

In the spirit of sharing / OSS, I would like to see another field added to the .nuspec file, that contains a URL to the source for the package install.

I know this strays a bit from the original [nuspec reference](http://docs.nuget.org/docs/reference/nuspec-reference), but I think if it were named `chocolateyProjectUrl` or similar, you have a pretty good chance of never conflicting with anything nuget adds in the future.

**Comment by ferventcoder** [comment]
I've moved this issue to https://github.com/chocolatey/choco/issues/205
