### ISSUE TITLE
Consider providing all functionality from single 'choc' (or similar) command

### ISSUE THREAD

**Issue by Iristyle** [chocolatey/chocolatey#186]
IMHO, it will improve adoption / discoverability if all chocolatey commands stem from a single entry point -- `choc` or whatever seems the most effectual.  I think most people will agree that `chocolatey` is a little slow to type (and easy to mistype ;0)

Just saw this tweet... 
https://twitter.com/MotoWilliams/status/259731598503723008

The issue is that Chocolatey has all these aliases to things that are inside `chocolatey` -- and the docs kind of push you in this direction.

* `cinst`
* `cuninst`
* `clist`
* `cpack`
* `cup`

Etc, etc... 

While these are convenient for people who know them, they're not really __discoverable__ to people who are new.  It's easy to remember one command -- a bit harder to remember a handful.

So I think that there are a few things that could be done to make the situation better

* Stress a single command entry point
* Better inline docs  - the output of `chocolatey /?` is an offender here.  Known issues, release notes  and legal stuff appear before the usage examples, for instance.
* Inline docs / aliases / profile registration in Powershell.  Powershell's built-in help system is fantastic and man-page like.  Using this (better) could go a really long way.
* A better landing page than the Wiki -- a fancy chocolatey.github.com that is noob friendly.  There's a lot going on at the chocolatey.org - I think it could be simplified with a focused landing page.

Other package manager command line ref examples (note they all have short, easy to type names ;0) - 

* [npm](https://npmjs.org/doc/)
* [pip](http://www.pip-installer.org/en/latest/usage.html)
* [gem](http://docs.rubygems.org/read/chapter/10)
* [nuget](http://docs.nuget.org/docs/reference/command-line-reference)
* [brew](http://mxcl.github.com/homebrew/)
* [apt-get](http://linux.die.net/man/8/apt-get)

I know you guys are already familiar with all of these.. links provided solely to document their command usage.

I love Chocolatey and will continue to build packages for it... but I see these areas as needing improvements (and yeah, I know I should probably use the forums for this ;0)

**Comment by ferventcoder** [comment]
This is called choco.
