### ISSUE TITLE
Chocolatey should not stop on error

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey#192]
When installing a batch of packages using the *packages.conf* XML trick, Chocolatey stops on a failing package, and skips the other packages.

You have to remove the finished packages from the XML, including the failed one, and try again. I think Chocolatey should just continue going, and mention the failed packages after everything is done. This way you can leave your computer unattended, knowing at least everything that doesn't fail will be installed once you get back.

Perhaps that last annoyance is what is talked about in issue #154, but I am not sure.

An idea is to have Chocolatey log all output and maybe error output separately, to a log file so you don't have to worry about error messages scrolling out of the viewable area of the command console.

(Filed as separate issue by request)

**Comment by ferventcoder** [comment]
Is this fixed in vCurrent?

**Comment by ferventcoder** [comment]
@rismoney oldie but a goodie. Now we have a ticket for ensuring full stop if there is a failure in the chain - https://github.com/chocolatey/choco/issues/1151
