### ISSUE TITLE
Add a helper function called Invoke-GenerateBinFile to replace the internal Generate-BinFile

### ISSUE THREAD

**Issue by zippy1981** [chocolatey/chocolatey#202]
The function would take an additional parameter of output path, and look like this:
https://github.com/zippy1981/Nuget-Packages-FerventCoder/blob/master/vim/tools/Invoke-GenerateBinFile.ps1

I have uncommitted code that does this.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/145
