### ISSUE TITLE
The underlying connection was closed:  Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by prongs** [chocolatey/chocolatey#252]
![image](https://f.cloud.github.com/assets/396205/189510/e77d7e8c-7e8c-11e2-92d5-34e801621ff5.png)

Any idea why this might be happening? I am behind a proxy. Could that be causing any problems?

**Comment by ggrussenmeyer** [comment]
Just for information, after struggling with the exact same error message for a few hours, it tunred out that the certificate of the root CA that delivered the chocolatey.org certificate (Go Daddy Root Certificate Authority - G2) was not present int my Windows trusted root CA certificate store (although present in Firefox own's trust store).
Importing it manually in the Windows store fixed the issue.

**Comment by esters** [comment]
@ggrussenmeyer thank you for the information. I had the same issue on Windows XP. Importing the GoDaddy Class 2 Certification Authority Root Certificate - G2 (https://certs.godaddy.com/repository/gdroot-g2.crt) solved the issue.

**Comment by nturley** [comment]
I had this problem on a clean windows install. I opened internet explorer. Allowed it to update (presumably updating it's certificates). That solved the problem.

**Comment by ferventcoder** [comment]
For anyone else that comes across this link - https://github.com/chocolatey/choco/wiki/Proxy-Settings-for-Chocolatey
