### ISSUE TITLE
Cache clean

### ISSUE THREAD

**Issue by Iristyle** [chocolatey/chocolatey#253]
NPM ([cache clean](https://npmjs.org/doc/cache.html)), Bower ([cache-clean](https://github.com/twitter/bower#usage)) and others have a facility for cleaning their local cache, either by package name, or for all packages.

I think this is an important feature to have in Chocolatey as well, because we're running into some scenarios where a package with a bunch of dependencies can fail halfway through.  This usually involves me telling people to manually find their chocolately `lib` folder and start deleting stuff.

It would be useful to issue a simple clean command to delete the package and all it's listed dependencies, so that a reinstall can be attempted without resorting to manually sifting through the package list.  In our experience, `--force` doesn't really address this.

**Comment by ferventcoder** [comment]
--force --force-dependencies (or -fx)

**Comment by ferventcoder** [comment]
This is now linked up with https://github.com/chocolatey/choco/issues/1124 so please follow from there.
