### ISSUE TITLE
cpack/cpush returns zero exit code even when error occurs

### ISSUE THREAD

**Issue by activescott** [chocolatey/chocolatey#256]
I'm automating cpack in a build script and it is returning a zero exit code despite the fact it writes an error "Could not find a part of the path..." - The nuspec path I fed it on the command line is just wrong. I can't catch it in the build script feasibly though without a good exit code.

**Comment by jbuedel** [comment]
This still happens in at least one situation. See below where I have passed an invalid $version$ token.
![badversion](https://cloud.githubusercontent.com/assets/85681/10548068/fbe22a4e-73fd-11e5-8bc9-c2f1053fa16b.png)

**Comment by ferventcoder** [comment]
Let's file a new issue about this over at chocolatey/choco.

On Friday, October 16, 2015, Josh Buedel <notifications@github.com> wrote:

> This still happens in at least one situation. See below where I have
> passed an invalid $version$ token.
> [image: badversion]
> <https://cloud.githubusercontent.com/assets/85681/10548068/fbe22a4e-73fd-11e5-8bc9-c2f1053fa16b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/256#issuecomment-148773726>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by jbuedel** [comment]
New issue created. https://github.com/chocolatey/choco/issues/469

**Comment by ferventcoder** [comment]
Thanks!

On Friday, October 16, 2015, Josh Buedel <notifications@github.com> wrote:

> New issue created. chocolatey/choco#469
> <https://github.com/chocolatey/choco/issues/469>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/256#issuecomment-148840199>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder
