### ISSUE TITLE
[Enhancement] --noop command

### ISSUE THREAD

**Issue by stack72** [chocolatey/chocolatey#263]
Hi 

From my use of puppet, I have become very fond of the --noop command. This basically allows me to check a configuration against a server and get the result of what puppet would have done without actually doing it. This basically means its a simulation of the event

I'd love there to be a cinst notepadplusplus --noop option to let me know what would happen if I tried to do an install or an update without actually applying it

PAul

**Comment by ferventcoder** [comment]
This is done - it's called `--noop`, but you can also use `--whatif` to invoke the same behavior. It's a core switch. https://github.com/chocolatey/choco/wiki/CommandsReference#default-options-and-switches
