### ISSUE TITLE
[Bug] cpack silently fails when dependency .NET 4.0+ is not met

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey#270]
`cpack` doesn't mention that there has been a problem, the package is just not generated.
Upon further investigation it turns out that .NET4.0+ is required for nuget.

This makes [DotNet4.0](http://chocolatey.org/packages/DotNet4.0) a funny Chocolatey package, because you need it installed before you can install it. :P

**Comment by ferventcoder** [comment]
Nothing works in choco.exe without .NET 4.0. So there will be a very visible error.
