### ISSUE TITLE
[BUG] Uninstall-ChocolateyPackage.ps1 does not use the msifile

### ISSUE THREAD

**Issue by DennisHaper** [chocolatey/chocolatey#286]
The msi file is never set as an arguement when trying to uninstall. Thus, when msiexec is called, it is just passed /x as well as any other flags, but the file is never passed.

The symmetrical code can be used as an example (Install-ChocolateyInstallPackage.ps1):
Line:58
if ($fileType -like 'msi') {
    $msiArgs = "/i `"$file`"" 

However, Uninstall-ChocolateyPackage.ps1 has:
Line: 50

if ($fileType -like 'msi') {
    $msiArgs = "/x"

**Comment by ferventcoder** [comment]
This has been moved over to choco - https://github.com/chocolatey/choco/issues/229
