### ISSUE TITLE
Remove the need to reopen the terminal when installing

### ISSUE THREAD

**Issue by glennblock** [chocolatey/chocolatey#350]
Currently whenever I install with chocolatey I need to reopen my terminal as it adds a new variable to the path.

npm doesn't require this as it has a central folder which is in the path which cmd files are added to for each global module. uninstalling removes the cmd from that location.

the cmd in this case would change to the directory where the chocolatey app is installed and run it passing in any args.

**Comment by ferventcoder** [comment]
Old one that is fixed
