### ISSUE TITLE
Provide way to uninstall ALL versions of an app

### ISSUE THREAD

**Issue by codearoo** [chocolatey/chocolatey#389]
and also.. to provide parameters of the sub-commands. For example, I would expect this:
choco uninstall /?         or    cuninst /?
to show me special options just for the un-install process.

There it would make sense to have something like a    -all  option to remove ALL versions of an app, not just the last one.

example usage:
cuninst putty -all

because otherwise, you have to repeatedly issue  'cuninst putty'  until all versions are finally gone.

**Comment by ferventcoder** [comment]
`choco uninstall pkgname --all-versions`
