### ISSUE TITLE
Chocolatey Install Fails With Error Messages

### ISSUE THREAD

**Issue by AlexRussak** [chocolatey/chocolatey#402]
Hello,

I'm unable to install Chocolatey on Windows 8.1 Enterprise.
I tried running the command via command line and when that failed (got the same error), I tried Powershell directly.

If I navigate to the 7za.exe file and attempt to run it, I get an error message:
![image](https://f.cloud.github.com/assets/890967/1875294/1c3b7db0-78ef-11e3-945d-58b631926b8e.png)

I tried disabling SmartScreen & UAC and got the same result.

![image](https://f.cloud.github.com/assets/890967/1875283/8c90db74-78ee-11e3-8223-9dc2e013b804.png)

```
PS C:\Users\Alex> iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
Downloading http://chocolatey.org/api/v2/package/chocolatey/ to C:\Users\Alex\AppData\Local\Temp\chocolatey\chocInstall\
chocolatey.zip
Download 7Zip commandline tool
Downloading https://github.com/chocolatey/chocolatey/blob/master/src/tools/7za.exe?raw=true to C:\Users\Alex\AppData\Loc
al\Temp\chocolatey\chocInstall\7za.exe
Extracting C:\Users\Alex\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\Alex\AppData\Local\Temp\ch
ocolatey\chocInstall...
Start-Process : This command cannot be run due to the error: The specified executable is not a valid application for
this OS platform..
At line:47 char:1
+ Start-Process "$7zaExe" -ArgumentList "x -o`"$tempDir`" -y `"$file`"" -Wait
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Installing chocolatey on this machine
& : The term 'C:\Users\Alex\AppData\Local\Temp\chocolatey\chocInstall\tools\chocolateyInstall.ps1' is not recognized
as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:58 char:3
+ & $chocInstallPS1
+   ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Alex\A...ateyInstall.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Ensuring chocolatey commands are on the path
PS C:\Users\Alex> chocolatey
chocolatey : The term 'chocolatey' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ chocolatey
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (chocolatey:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by jnm2** [comment]
I'm getting the exact same error on Windows Server 2012 R2, using the admin command prompt command. I manually downloaded 7za.exe and chocolatey.zip and tried again and nothing changed. I eventually decided to extract the zip manually and tried the install command and the first error showed up but the install finished successfully.

However, installs all fail with `The underlying connection was closed: An unexpected error occurred on a send.`

It would be nice to be given a list of things to troubleshoot when this happens.

**Comment by ferventcoder** [comment]
I'm not sure that your error has the same causation as those from a couple of years ago. The 7za.exe and choco come from https://chocolatey.org now.

**Comment by ferventcoder** [comment]
@jnm2 Can you log this recent issue to choco instead of this repository?

**Comment by jnm2** [comment]
I'm certain you're right about that. Sure thing. https://github.com/chocolatey/choco/issues/662
