### ISSUE TITLE
[BUG] Unzip specific folder feature is broken after introducing 7zip

### ISSUE THREAD

**Issue by AnthonyMastrean** [chocolatey/chocolatey#406]
I'm updating a package that downloads an archive with x64 and Win32 subdirectories. I used to extract the entire thing and manually remove the unneeded components. But, I figured I would try the as-yet undocumented `-specificFolder` parameter of `Install-ChocolateyZipPackage`.

```powershell
$name   = "bellavista"
$url    = "http://.../bellavista.zip"
$tools  = Split-Path $MyInvocation.MyCommand.Definition
$folder = if(Get-ProcessorBits 64) { "x64" } else { "Win32" }


Install-ChocolateyZipPackage -PackageName $name -Url $url -UnzipLocation $tools -SpecificFolder $folder
```

But, it didn't work. The first thing I saw was a goofy log message. Look at the "full path" in bold. It contains a non-path

> "Extracting **c:\users\foo\temp\chocolatey\bellavista\bellavistaInstall.zip\x64** to c:\Chocolatey\lib\bellavista.1.0\tools..."

And, digging in [the source][1], I saw a bad 7za command line being constructed

```batch
7za x -o"c:\Chocolatey\lib\bellavista.1.0\tools" -y "c:\users\foo\temp\chocolatey\bellavista\bellavistaInstall.zip\x64"
```

From my reading of [the command line reference][2], and hacking my helper function, the correct command line should be...

```batch
7za x "c:\users\foo\temp\chocolatey\bellavista\bellavistaInstall.zip -o"c:\Chocolatey\lib\bellavista.1.0\tools" "x64" -y
```

And, actually, with this fix, you could supply *any glob pattern* to 7za, not just a specific folder.

 [1]: https://github.com/chocolatey/chocolatey/blob/master/src/helpers/functions/Get-ChocolateyUnzip.ps1#L71
 [2]: http://sevenzip.sourceforge.jp/chm/cmdline/commands/extract_full.htm

**Comment by rubenqba** [comment]
When is solved this issue??

**Comment by ferventcoder** [comment]
Migrated to https://github.com/chocolatey/choco/issues/676
