### ISSUE TITLE
Compact cver option

### ISSUE THREAD

**Issue by adamralph** [chocolatey/chocolatey#414]
When checking what needs updating with cver, the output is very bloated and requires a lot of scrolling to view, e.g.
![image](https://f.cloud.github.com/assets/677704/2074761/5e21660e-8d80-11e3-93b9-48e372c4e146.png)

I'd like to see nice compact output like the following:

```
Name            Installed           Available           Upgradable 
=============== =================== =================== ==========
7zip            9.22.01.20130618    9.22.01.20130618    
7zip.install    9.22.01.20130618    9.22.01.20130618    
Console2        2.0.148             2.0.148
fiddler4        4.4.5.8             4.4.5.920130128     Y
git             1.8.4               1.8.5.2             Y
git.install     1.8.4               1.8.5.2             Y
...
```

Perhaps the current output can stay as the default with the compact output as an option. Or perhaps the compact should be the default with the verbose being an option.

**Comment by ferventcoder** [comment]
How does this look? 

This uses limitoutput option (`-r`) to keep the information relevant. `false` at the end tells you whether it is pinned or not:
c:\> choco upgrade all --noop -r
linqpad|2.46.09|4.51.03|false
grepwin|1.6.1|1.6.6|false
vim|7.4.27|7.4.560|false
sumatrapdf.commandline|2.5.2|3.0|false
notepadplusplus.install|6.7.3|6.7.4|false
mingw|4.8.1.20140107|4.8.3.20141208|false
1password|1.0.9.341|4.1.0.530|false
notepadplusplus.commandline|6.7.2|6.7.4|false
PowerShell|4.0.20140915|4.0.20141001|false
autohotkey|1.1.16.05|1.1.19.02|false
webpicommandline|7.1.40719.0|7.1.50430.0|false
chocolatey.server|0.1.0|0.1.1|false
wincommandpaste|1.0.6|1.0.8|false
git|1.9.4|1.9.5.20150114|false
javaruntime|7.0.51|7.0.75|false
gitextensions|2.47.3|2.48.03|false
fiddler|2.4.5.3|2.4.9.8|false
VirtualCloneDrive|5.4.6.20130920|5.4.7.0|false
ChocolateyPackageUpdater|0.6.2.0|0.6.4.0|false
git.commandline|1.9.4|1.9.5|false
TestDriven.Net|3.3.2779|3.5.2830|false
DotNet3.5|3.5|3.5.20140403|false
resharper|8.0.2000.2660|9.0.1|false
yumi|2.0.0.8|2.0.1.5|false
notepadplusplus|6.7.3|6.7.4|false
autohotkey.install|1.1.16.05|1.1.19.02|false
papercut|2013.6.10.2|2014.11.5|false
puppet|3.7.0|3.7.4|false
ccleaner|4.17.4808|5.02.5101|false
keepass.portable|2.27|2.28|false
sumatrapdf|2.5.2|3.0|false
pip|1.1.1|1.2.0|false
ruby.devkit|4.5.2.20111231|4.5.2.20120101|false
boxstarter.chocolatey|1.0.33|2.4.159|false
autohotkey_l|1.1.11.01|1.1.14.20140119|false
DotNet4.0|4.0.30319.20130222|4.0.30319.20141222|false
ketarin|1.6.0.434|1.7.1|false
nodejs|0.10.30|0.10.36|false
autohotkey.portable|1.1.18.00|1.1.19.02|false
Pester|2.0.2|3.3.5|false
WindowsLiveWriter|2011.0.0|2012.0.0|false
dropbox|2.8.4|3.0.5|false
webpicmd|7.1.50430.0|7.1.50430.20141001|false
```

**Comment by adamralph** [comment]
A table would be better but I can understand the difficulty in determining column widths. Perhaps a space either side of the pipe symbol would be a bit more readable?

What do you mean by 'pinned'?

**Comment by ferventcoder** [comment]
That did just point out a possible bug in new choco install logic. **NOTE**: It believes chocolatey 0.9.8.23 is installed. :/

**Comment by ferventcoder** [comment]
Pinned, means you "pin" to a particular version. It's a way to suppress upgrades...

**Comment by ferventcoder** [comment]
Dang it, not a bug... :/

**Comment by ferventcoder** [comment]
Attempting to upgrade shows the proper version:
![image](https://cloud.githubusercontent.com/assets/63502/5993780/eb32d902-aa20-11e4-884b-edf0e213b637.png)

It's there in the package directory:
![image](https://cloud.githubusercontent.com/assets/63502/5993782/04f657ec-aa21-11e4-94f8-122982545521.png)

Anyone want to guess what I forgot to pass? Yes, `-pre`. I think localonly should always prefer the prerelease. So it's a bug.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/46 (and fixed)

**Comment by ferventcoder** [comment]
FYI, the -r option is meant for machines to read, not humans.
