### ISSUE TITLE
Use the "highest" dependency version setting when resolving dependencies with nuget

### ISSUE THREAD

**Issue by AnthonyMastrean** [chocolatey/chocolatey#415]
I often have sets of packages like `foo`, `foo.install`, and `foo.portable`, where the default package simply depends on the install package. I usually set a thoughtful, but loose version range so I wouldn't have to constantly update the default package.

For example, depend on any version in  the 1.x major range.

```xml
<dependency id="foo.install" version="[1.0, 2.0)" />
```

However, the default resolution was to pick the _lowest_ major & minor versions that satisfy those criteria. So, even if I published an install package at 1.1, 1.2, and so on, you would never get those from installing the default package.

So, I end up being more restrictive with the version range specification and updating the default package more often anyway :(

NuGet 2.8 introduces [finer grained control][1] over dependency resolution. It seems to make sense for me, the wider audience of package maintainers, and the intentions of Chocolatey to select the _highest_ dependency version that satisfies.

```bat
nuget.exe ... -DependencyVersion Highest
```

What do you think?

 [1]: http://docs.nuget.org/docs/release-notes/nuget-2.8

**Comment by nabheet** [comment]
Does chocolatey support any kind of version range specification like "[1.1, 2.0)"?

**Comment by ferventcoder** [comment]
@nabheet yes in the nuspec.

**Comment by ferventcoder** [comment]
@AnthonyMastrean NuGet indeed did introduce Dependency Resolution strategy, but they didn't expose it as all in NuGet.exe. Sad but no matter as choco.exe does it just fine. https://github.com/chocolatey/choco
