### ISSUE TITLE
Behavior when one choco source is unavailable

### ISSUE THREAD

**Issue by bill-long** [chocolatey/chocolatey#422]
We have an internal-only NuGet feed that has some Chocolatey packages. We can choco add source and install stuff from it on the internal network and life is good. The problem arises for mobile users.

A user on a laptop that connects to the internal network via DirectAccess or VPN will only have access to the internal network some of the time, so the internal-only choco source won't always be available. And when it isn't available, a lot of stuff breaks:

```
C:\> cinst sysinternals
Chocolatey (v0.9.8.23) is installing 'sysinternals' and dependencies. By installing you accept the license for 'sysinter
nals' and each dependency you are installing.
The HTTP request was forbidden with client authentication scheme 'Negotiate'.

Command 'install' failed (sometimes this indicates a partial failure). Additional info/packages: sysinternals
Reading environment variables from registry. Please wait... Done.
C:\> cver
The HTTP request was forbidden with client authentication scheme 'Negotiate'.


found         : 0.9.8.23
name          : chocolatey
latestCompare : 000000000000
verMessage    : Your version is newer than the most recent. You must be smarter than the average bear...
latest        : {}
foundCompare  : 000000000000.000000000009.000000000008.000000000023



Reading environment variables from registry. Please wait... Done.
C:\> cver sysinternals
The HTTP request was forbidden with client authentication scheme 'Negotiate'.


found         : 2014.02.04
name          : sysinternals
latestCompare : 000000000000
verMessage    : Your version is newer than the most recent. You must be smarter than the average bear...
latest        : {}
foundCompare  : 000000002014.000000000002.000000000004
```

This is because it's trying to connect to the internal choco source, but that source sees the external IP and denies access. Cinst does work if you specify the -source explicitly in this scenario.

When Chocolatey gets an error connecting to one particular source, it would be better to report the error and then continue down the list of sources. Failure to access one source shouldn't force you to specify -source or break stuff that doesn't take a -source parameter.

**Comment by metalseargolid** [comment]
Running 0.10.2

I can confirm this is happening for me but when running `choco search` (converse to the post i can install packages when none of my VPN-only sources are available). Though as a workaround i can specify `-s chocolatey` when searching for now, it's a bit hamhanded.

What's also strange is that it seems to work fine for the few minutes following me disconnecting from the VPN.

**Comment by ferventcoder** [comment]
This particular issue is at https://github.com/chocolatey/choco/issues/612 (and not necessarily related to what this was originally, because we have an even newer version of NuGet than was suggested earlier in this post).

@metalseargolid can you perhaps move your comment over to that thread? Thanks!
