### ISSUE TITLE
Deprecate aliases like “cpack”

### ISSUE THREAD

**Issue by flyx** [chocolatey/chocolatey#431]
`cpack` is already part of the popular [CMake][1] utility suite. Please consider renaming chocolatey's `cpack` to avoid confusion and name clashes.

 [1]: http://cmake.org/

**Comment by paulsapps** [comment]
I have this problem on appveyor when trying to run cmake's cpack, what has to be executed to removoe the aliases?

**Comment by ferventcoder** [comment]
@paulsapps - You should delete `c:\programdata\chocolatey\bin\cpack.exe` as a workaround for now. Or you can try to update the path so that cmake's cpack evaluates first on the path.

**Comment by paulsapps** [comment]
thanks I'll give it a go

**Comment by pyhedgehog** [comment]
Only thing I see usable is `cup` because there is a mess between `choco update` and `choco upgrade`.

**Comment by ferventcoder** [comment]
Issue moved to https://github.com/chocolatey/choco/issues/89
