### ISSUE TITLE
List packages with available updates

### ISSUE THREAD

**Issue by lawrencejohnston** [chocolatey/chocolatey#435]
It would be very useful to be able to list packages with available updates.

My use case is that I want to have a good idea of what "cup all" is going to do before I do it.

Previously requested here: https://groups.google.com/forum/#!msg/chocolatey/KC87guFjZWM/gvn4E-wPNR8J

And mentioned in #320.

**Comment by chucker** [comment]
This is essentially covered with 'cup all -noop'.

**Comment by ferventcoder** [comment]
@chucker you can also `cup all --noop -r`

But this specific case will be covered with an `outdated` command - https://github.com/chocolatey/choco/issues/170
