### ISSUE TITLE
Update-SessionEnvironment overwrites user-made customizations in the current PS session

### ISSUE THREAD

**Issue by jberezanski** [chocolatey/chocolatey#475]
Example scenario:
1. open Developer Command Prompt for VS2013 - this sets a bunch of environment variables and puts several tools on PATH (e.g. msbuild)
2. start powershell
3. confirm the dev tools are available: msbuild /?
3. invoke chocolatey.ps1 to install some package: ````& $Env:ChocolateyInstall\ChocolateyInstall\chocolatey.ps1 install fciv````
4. the dev tools are no longer available: msbuild /? responds with "the term 'msbuild' is not recognized..."

The cause is that Update-SessionEnvironment simply overwrites environment variables with values saved in the registry. This is especially painful with regard to PATH, but also interferes with, for example, an attempt to set ChocolateyInstall to a temporary location in order to test a new build of Chocolatey.

I believe the feature should be rewritten to actually detect environment changes caused by the packages (by taking a snapshot of the environment in the registry before calling the package install script and comparing it with the state in the registry after the script finishes) and apply only the detected changes to the current environment.

Side note: care should also be taken to clean up environment variables internally used by Chocolatey itself (e.g. chocolateyPackageFolder, ChocolateyEnvironmentDebug) - ideally, stop using them in favor of plain Powershell variables, but as a quick fix, remove those variables as soon as they are not needed anymore.

**Comment by ferventcoder** [comment]
I believe this is fixed as of 0.9.10.3, further in 0.10.0, and has one outstanding issue to be fixed.

### 0.9.10.x
* Refresh environment between packages, ensure process variables stay set - https://github.com/chocolatey/choco/issues/439
* In PowerShell, do not update PSModulePath - https://github.com/chocolatey/choco/issues/295

### 0.10.0
* Capturing additional PSModulePath process items and making them available for the Internal PowerShell Host - https://github.com/chocolatey/choco/issues/830

### Further fixes for Update-SessionEnvironment 
* Ensure refresh while running in PowerShell doesn't wipe out variables - https://github.com/chocolatey/choco/issues/129

**Comment by ferventcoder** [comment]
The last one may not be required.
