### ISSUE TITLE
Regresson in ordering in cver all in 0.9.8.27

### ISSUE THREAD

**Issue by adamralph** [chocolatey/chocolatey#530]
OK, perhaps calling it a regression is a bit harsh, but in 0.9.8.25, `cver all` would return the apps in alphabetical order. In 0.9.8.27 the order seems all jumbled up.

**Comment by ferventcoder** [comment]
This is fixed in choco.exe. Everything is happily in abc order again.

**Comment by adamralph** [comment]
nice! :+1:
