### ISSUE TITLE
Install Aware MSI don't like to be renamed

### ISSUE THREAD

**Issue by jamiecook** [chocolatey/chocolatey#538]
You wouldn't think it was still an issue in this day and age but apparently install aware does some very funny stuff with their msi which precludes you from renaming them. 

http://www.installaware.com/forum/viewtopic.php?f=2&t=5532

(best reply from tech illiterate support I've ever seen in that forum)

The solution for this very specific problem comes from here I think: 

https://github.com/chocolatey/chocolatey/blob/master/src/helpers/functions/Install-ChocolateyPackage.ps1#L77

If instead of downloading the file to a ${App}Install.${EXTENSION} it just used the original filename it would avoid this particular problem.
I am probably missing something very important about why it uses the alternate filename though

**Comment by ferventcoder** [comment]
Migrated to https://github.com/chocolatey/choco/issues/435
