### ISSUE TITLE
[Enhancement] Please add proxy config 

### ISSUE THREAD

**Issue by netroby** [chocolatey/chocolatey#546]
please add proxy config command.
such as 
```
cinst config proxy.type   http
cinst config proxy.ip    10.0.18.88
cinst config proxy.port 8123
```

do not force me change ie proxy setting by hand.
chocolatey should had it's own proxy setting

**Comment by ferventcoder** [comment]
Closing for now, this isn't really something we want in there yet. If this is needed, I'm sure it will come up again in the new choco.
