### ISSUE TITLE
[suggestion] Include release notes in GitHub release feed

### ISSUE THREAD

**Issue by kwill** [chocolatey/chocolatey#567]
I would like to watch the GitHub release feed available at https://github.com/chocolatey/chocolatey/releases.atom (equivalent to the https://github.com/chocolatey/chocolatey/releases web page). Would it be possible for future releases to include the content from https://github.com/chocolatey/chocolatey/wiki/ReleaseNotes in that feed?

(I have of course subscribed to the newsletter already ;)

**Comment by ferventcoder** [comment]
Done, but over here https://github.com/chocolatey/choco/releases.atom
