### ISSUE TITLE
Chocolatey-Install should return non-zero exit code if chocolateyInstall.ps1 fails

### ISSUE THREAD

**Issue by warnergodfrey** [chocolatey/chocolatey#568]
If a package's install script fails and exits with a non-zero exit code then choco install still returns with a zero exit code. This behaviour is consistent in both v0.9.8.27 and v0.9.8.28-alpha2.

Run-ChocolateyPS1 throws an error if the chocolateyInstall.ps1 or chocolateyUninstall.ps1 fails, however the Chocolatey-NuGet.ps1 swallows the exception. The exception should bubble up and cause the choco command to fail.

**Comment by bmedlin** [comment]
I've had the same problem. The exception thrown from my package's chocolateyInstall.ps1 is not bubbling up - it is being caught in Chocolatey-Nuget.ps1 and not re-thrown (~line 93). There appears to be an attempt to fail the package by setting $chocolateyErrored to $true, but this variable is false again by the time it is evaluated in chocolatey.ps1. Re-throwing the exception appears to resolve the issue.

**Comment by ferventcoder** [comment]
@warnergodfrey @bmedlin I believe this was just fixed by @mwrock  in a recent PR.

**Comment by ferventcoder** [comment]
#68

**Comment by mwrock** [comment]
my PR addresses the exit code but does not rethrow. Honestly I personally prefer actually rethrowing the actual exception. For something like Boxstarter which calls the chocolatey powershell functiuons directly, I can better inspect the exception and provide better logging. I realize that will no longer be possible with choco.exe.

Another PR I considered was adding more detail to the exceptions logged. Currently chocolotey just captures the error message which is sometimes not very helpful. Doing something like logging:

```
$_.exception | fl * -force | out-string
```
would capture any stacktrace and inner exceptions and even script level stack trace on later OSs. I'm probably gonna hold off on contributing that until the new chocolatey comes out but this is my 2 cents. :)

Also, chocolatey simply returns an exit code of 1 and it would be better to at least return the original exit code. My PR was just an attempt to "fix" what appeared to be the current intent of the code. On the boxstarter side I can always just examine the `$errors` array to grab the full exceptions after the fact. Again, that only works if you are calling chocolatey from powershell and calling the actual powershell functions so you are not crossing any process boundaries.

**Comment by ferventcoder** [comment]
@mwrock where would you put that bit of code?

**Comment by ferventcoder** [comment]
@mwrock nevermind, found a good spot. :)
