### ISSUE TITLE
shims stay open while applications run

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/chocolatey#585]
When I start an application using its shim, the shim remains open as a big black window, wasting space on screen, in Alt-Tab and in the task bar.

Example packages: procexp, procmon, dbgview

**Comment by ferventcoder** [comment]
As an enhancement here, I added https://github.com/chocolatey/shimgen/issues/13 and fixed it  for 0.9.9 - https://github.com/chocolatey/choco/commit/fac7727b183f44b217cc064486171404c30b6622
