### ISSUE TITLE
Choco install command suddenly became case sensitive!!!???

### ISSUE THREAD

**Issue by codearoo** [chocolatey/chocolatey#589]
We used ver ...23 for a while, and updated to ...27 some weeks ago.

choco install packagename --source "my custom source"

choco install PackageName --source "my custom source"

These are not the same.. it should not care what case the package name is.

**Comment by ferventcoder** [comment]
@codearoo can you let me know if this is still an issue with the latest prerelease of choco (put it on a canary system, it's choco.exe).

**Comment by ferventcoder** [comment]
I'm going to call it fixed for now pending your response.

**Comment by codearoo** [comment]
Yes this still is not fixed. I just tested on ver .32.

**Comment by ferventcoder** [comment]
Sorry, I meant with version 0.9.9 (prerelease). Test on a non production
system please. It would be great if this can be closed with 0.9.9, I
believe it is fixed, I just don't have a source like proget that has this
issue.

On Wednesday, January 28, 2015, codearoo <notifications@github.com> wrote:

> Yes this still is not fixed. I just tested on ver .32.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/589#issuecomment-71832010>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by codearoo** [comment]
oh.. I don't know where to get that version.
would I do this?
choco install chocolatey -Version 0.9.9.0  ??
I don't know where to see the list of valid beta versions.

**Comment by gep13** [comment]
You can find it here:

https://chocolatey.org/packages/chocolatey/0.9.9-alpha-20150125

`choco install chocolatey -Pre`

**Comment by gep13** [comment]
> I don't know where to see the list of valid beta versions.

The versions of a particular package are shown at the bottom of each package page.

**Comment by codearoo** [comment]
I didn't know how to find this alpha pre-release page.

anyway, I tried it with ver 0.9.9 and this issue seems resolved.

The install and removal of the pre-release version, however, is not working. :)  Installing with   "-pre" did work (with some errors) but then per instructions on the screen to --force 0.9.8.32  failed. So now that test system can't get out of pre-release.

**Comment by gep13** [comment]
> I didn't know how to find this alpha pre-release page.

From any package version page, i.e:

https://chocolatey.org/packages/chocolatey/0.9.8.32

Scroll to the bottom, and you will see:

![image](https://cloud.githubusercontent.com/assets/1271146/5938971/b46c68e2-a6f7-11e4-8f01-32e884b8651c.png)

Where you can then see *all* available package versions, including pre-release.

**Comment by ferventcoder** [comment]
Why I asked for you not to do it on a prod system. Downgrading requires
removing some files, although you can probably just use the
chocolatey.org/install.ps1 script and it should work.

On Wednesday, January 28, 2015, Gary Ewan Park <notifications@github.com>
wrote:

> I didn't know how to find this alpha pre-release page.
>
> From any package version page, i.e:
>
> https://chocolatey.org/packages/chocolatey/0.9.8.32
>
> Scroll to the bottom, and you will see:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1271146/5938971/b46c68e2-a6f7-11e4-8f01-32e884b8651c.png>
>
> Where you can then see *all* available package versions, including
> pre-release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/589#issuecomment-71840294>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by codearoo** [comment]
It was a test system..but still want to get it back.. and thought I should
let you know

I'll brute force it if your suggestion does not work.

**Comment by ferventcoder** [comment]
Let me know if it doesn't work. It should. I haven't tried a `choco install chocolatey --version 0.9.8.32 --force`

**Comment by ferventcoder** [comment]
Although doing exactly that seems to have worked for me.

![image](https://cloud.githubusercontent.com/assets/63502/5939894/127e0574-a6cd-11e4-99f1-bd8c26932b1e.png)

**Comment by ferventcoder** [comment]
Update: replaced image... for some reason the last capture cut off the bottom

**Comment by ferventcoder** [comment]
Interestingly enough, I would have thought there would be more output from the install.

**Comment by codearoo** [comment]
choco install chocolatey --force --version 0.9.8.32

that worked...  somehow when I ran it I omited the   "--version" part... it
was doing something... not sure what then.
