### ISSUE TITLE
Chocolatey incorrectly adds things to PATH multiple times

### ISSUE THREAD

**Issue by DanTup** [chocolatey/chocolatey#591]
My path currently looks like this:

    M:\Apps\dart-sdk\bin;C:\Users\Danny\AppData\Roaming\Pub\Cache\bin;M:\Apps\dart-sdk\bin;C:\Users\Danny\AppData\Roaming\Pub\Cache\bin;M:\Apps\dart-sdk\bin;C:\Users\Danny\AppData\Roaming\Pub\Cache\bin;

My install script looks like this:

    Install-ChocolateyPath "$installDir\bin"
    Install-ChocolateyPath "${env:USERPROFILE}\AppData\Roaming\Pub\Cache\bin"
    $env:Path = "$($env:Path);$installDir\bin;${env:USERPROFILE}\AppData\Roaming\Pub\Cache\bin"

As I understand it, the bottom line doesn't save anything back to PATH in Windows, it's only for the current session. This makes me think that `Install-ChocolateyPath` is adding things to path when they already exist.

**Comment by ferventcoder** [comment]
This is fixed by https://github.com/chocolatey/choco/issues/303 I believe, and further fixed by https://github.com/chocolatey/choco/issues/699
