### ISSUE TITLE
PATH changes (for current console session) in chocolateyInstall do not appear to work

### ISSUE THREAD

**Issue by DanTup** [chocolatey/chocolatey#592]
In my chocolatey install, I have this:

    Install-ChocolateyPath "$installDir\bin"
    Install-ChocolateyPath "${env:USERPROFILE}\AppData\Roaming\Pub\Cache\bin"
    $env:Path = "$($env:Path);$installDir\bin;${env:USERPROFILE}\AppData\Roaming\Pub\Cache\bin"

However, after running the install, the current `PATH` is not updated.

Based on some other strange behaviour, it feels like `cinst` might be calling powershell.exe (creating a new session), which means the path change does not persist once it drops back out to the original session?

**Comment by ferventcoder** [comment]
We are going to be adding a module for update-sessonenvironment so you can do this in powershell. Look for that over in https://github.com/chocolatey/choco
