### ISSUE TITLE
Clean command

### ISSUE THREAD

**Issue by ghost** [chocolatey/chocolatey#595]
As [has been mentioned](307#issuecomment-23800777), Chocolatey could benefit
from a `clean` command. This could be run like

```
choco clean
```

Or

```
choco clean foo
```

where it removes the files for one or all packages from `%TEMP%\chocolatey`.

**Comment by svnpenn** [comment]
@ferventcoder is this fixed?

**Comment by ferventcoder** [comment]
Closed as a duplicate. Sorry, mentioned that awhile ago. Just doing some issue triage and noticed it was still open.
