### ISSUE TITLE
Chocolatey behaves strange after ctrl+c

### ISSUE THREAD

**Issue by thigg** [chocolatey/chocolatey#608]
After aborting one chocolatey command with ctrl+c, the shell session seems to be broken. Everytime one launches a chocolatey command afterwards you get a message if you would like to abort.

There should be at least a message that one should not abort commands via ctrl+c.
(But it's quite useful during package creation)

**Comment by aronovgj** [comment]
ctrl+c works for me if i do it several times in a row.

**Comment by ferventcoder** [comment]
That is a command/batch issue and will not exist in the new compiled version of choco. It's an annoyance at best, but it is an issue with using batch files. The underlying process gets orphaned, but it still knows about it, so it keeps asking if you want to terminate the process.

You can observe this behavior by pulling up Process Explorer (Sysinternals)

**Comment by ferventcoder** [comment]
Other tools that use .cmd/.bat files that call out to executables will display this same behavior.

I'm closing this as a non-issue. A message would be good, but this issue should not exist in the new version of choco.exe.
