### ISSUE TITLE
lowercase ids

### ISSUE THREAD

**Issue by thigg** [chocolatey/chocolatey#609]
It seems like dependencies are only working with lowercase ids, independent what is stated on the feed.

On the feed, the name of the package is for example "DotNet4.5", but if I am trying this:

```xml
<dependencies>
        <dependency id="DotNet4.5" version="4.5.20120822" />
</dependencies>
```
it is not working. But if I am changing it to this:

```xml
<dependencies>
        <dependency id="dotnet4.5" version="4.5.20120822" />
</dependencies>
```

it works fine.

**Comment by ferventcoder** [comment]
Calling this closed as a duplicate, plus I think it is fixed in choco.exe.
