### ISSUE TITLE
Testing chocolateyInstall.ps1

### ISSUE THREAD

**Issue by svnpenn** [chocolatey/chocolatey#610]
So this is my current workflow

1. create `chocolateyInstall.ps1`
1. `cpack`
1. `cinst -source $pwd PackageName`

http://github.com/chocolatey/chocolatey/wiki/CreatePackagesQuickStart

However, I feel like I should be able to test `chocolateyInstall.ps1` without
step 2 and 3. How can I do this?

**Comment by ferventcoder** [comment]
1. create `chocolateyInstall.ps1`
 1. call choco install `pkg.nuspec` --force

**Comment by ferventcoder** [comment]
FYI - https://github.com/chocolatey/choco

**Comment by ferventcoder** [comment]
@jmbeach Howdy. It looks like you are missing something. However if you want to follow up, let's do that over at https://github.com/chocolatey/choco.

**Comment by jmbeach** [comment]
Sorry, didn't realize what the FYI meant
