### ISSUE TITLE
choco uninstall package does not remove all versions

### ISSUE THREAD

**Issue by 030** [chocolatey/chocolatey#632]
# Steps to reproduce

```
choco install eclipse -Version 4.4.1
choco install eclipse
```

results in:
eclipse.4.402
eclipse.4.4.1
# Current outcome

choco uninstall eclipse needs to be issued twice to remove both versions
# Expected outcome

Executing choco uninstall eclipse removes all versions

**Comment by ferventcoder** [comment]
Duplicate of #389
