### ISSUE TITLE
I'd like to contribute branding

### ISSUE THREAD

**Issue by juliankrispel** [chocolatey/chocolatey#640]
Hi. I'm a designer, frontend developer and windows user. Without chocolatey my life would be a lot harder so thank you!

I sometimes offer free branding services to [projects](http://clojurecup.com) [I really like](https://github.com/swannodette/om/issues/215).

I'd love to do contribute branding to chocolatey. Let me know if you'd approve.

Cheers!

Julian

**Comment by juliankrispel** [comment]
Right, I'm back in action after a long christmas break. Here are some first ideas.

Personally I'm not settled on anything yet, want to try out some other ideas, but please let me know your thoughts, it's your product after all.

![image](https://cloud.githubusercontent.com/assets/1188186/5734347/1d6c3542-9bb4-11e4-87c1-c88c097e5e91.png)
![image](https://cloud.githubusercontent.com/assets/1188186/5734352/2b0822ba-9bb4-11e4-96d7-f9b21d4b7b8e.png)

**Comment by gep13** [comment]
Noice!  Of the two, I think I prefer the top one :-)

What do you think @ferventcoder ?

The one thing I would say is that it does sort of remind me of the Commodore 64 logo.

**Comment by rismoney** [comment]
Can you describe some of the design choices?  I would like to understand the intent. Any hidden aspects like http://lov5-77.diply.com/love-eat/30-famous-logos-that-have-a-hidden-message/51404

**Comment by juliankrispel** [comment]
@gep13 good point. it does look a little like the commodore logo.

here's a revised version. I also just did a whole bunch of other versions, will upload them in a sec.

@rismoney other than having a windows drive letter on a stylized candybar there isn't really much extra meaning there, or hidden meaning.

![image](https://cloud.githubusercontent.com/assets/1188186/5757212/49459aae-9cb9-11e4-8d59-ac8f0a7fecf4.png)

**Comment by rismoney** [comment]
Ahh that's really interesting.  My thought was that it was a play on packaging.  I didn't realize it was chocolate :). I thought it was a box.  I really like it.  But would a transparent (no background) be the usage or would everything go yellowy?

**Comment by juliankrispel** [comment]
@rismoney helpful feedback thanks. I had a feeling it might be too stylized to be recognizable.

So another idea I've had was to take it a step further and make it look a lot more like a chocolate bar brand.

So the first thing I did was to hand-letter the name in a curvy, indulgent kind of style, not to far removed from brands like catbury.

![image](https://cloud.githubusercontent.com/assets/1188186/5758218/9f0b9d58-9cc3-11e4-9ec8-e398b5f3d86e.png)

And then I played around with some varieties in different colours and different sizes. I think that could work quite well:

![image](https://cloud.githubusercontent.com/assets/1188186/5758375/67ed1f7a-9cc5-11e4-923c-b192e186ad66.png)

![image](https://cloud.githubusercontent.com/assets/1188186/5758380/78024426-9cc5-11e4-9378-649f8c0cc400.png)

![image](https://cloud.githubusercontent.com/assets/1188186/5758384/81b81702-9cc5-11e4-893c-a6b7cb8d9389.png)

![image](https://cloud.githubusercontent.com/assets/1188186/5758803/bd1f12de-9cc8-11e4-8859-9a9d23e9c92d.png)

![image](https://cloud.githubusercontent.com/assets/1188186/5758808/e0768122-9cc8-11e4-8d56-7a15b033ef1e.png)

![image](https://cloud.githubusercontent.com/assets/1188186/5758973/5978f040-9cca-11e4-8fc0-a17d20803a0c.png)

**Comment by ferventcoder** [comment]
Interesting. I'm really impressed with that latest design. It has less of a blocky feel.

Some things I like:

 * It captures the essence of a package that is being unwrapped to get to the inside, it's what's inside the package that counts.
 * The design is smooth. This signifies the process is a smooth transition from one state to another.
 * It's simple but not over simplistic. This signifies the essence of choco. A tool that is super simple to use and create packages with.
 * I think you are really starting to capture the essence of Chocolatey (as I described above).

Some things I'd like you to keep thinking about:

 * It should show a transition of moving from non-real to very real in a sense that you go from a concept of "choco install" to having real software on your machine.
 * I'm not in love with the packaging color. Would prefer some contrast between the chocolatey goodness in the wrapper but somewhat darker on the wrapping. Should still really stand out against a black background.

For the packages themselves, I feel that this would be too long. So perhaps an icon that is necessary as well. Some key points for an icon:

 * It should be square.
 * Still captures the essence of unwrapping a package to get to the goodness inside.
 * Is simple but not over-simplistic.
 * Looks good at 16x16 all the way up to 512x512. 
 * Maybe the current icon captures that already?

**Comment by ferventcoder** [comment]
updated my last set of comments a bit. @juliankrispel This is looking really good.

**Comment by rismoney** [comment]
I couldn't agree more with @ferventcoder comments.

Q: Is the chocolate candy wrapper  too much.  In other words does it not go too faraway from a computer thing to a candy bar, leaving nothing behind?  I see why you showed us the squared off 1 first as I think I am warming up to the 1st one, but I think the ":" colon is not needed.  choco will go well beyond windows

**Comment by juliankrispel** [comment]
@rismoney thanks I didn't know that there are plans for chocolatey on other platforms.

In answer to your question. From my experience branding doesn't have to be literal in a sense that it depicts the thing that it stands for i.e. machine package managing. It can be metaphorical. In fact the name 'chocolatey' already does exactly that, it's a metaphor for packaging/wrapping/containing software.

**Comment by juliankrispel** [comment]
@ferventcoder thanks for your extensive feedback, super helpful.

So firstly I should have been a little bit clearer. The big chocolate bar with wrapping isn't really a logo in the traditional sense that it works in all sizes. It's more like a treatment of the logo, an illustration.

The idea is that you can represent your brand in different ways as long as you keep some similarities that make it identifiable. Different versions for different purposes. A large one with more detail could be used for display purposes like the header of a homepage or an ad, or a tshirt, or something like that. 

And a smaller version would then be used for such things as favicons, app icons (like the gui) etc. I've included icons in my last post but here are another couple of treatments, in different sizes:

![image](https://cloud.githubusercontent.com/assets/1188186/5761266/a62af68a-9cda-11e4-953f-0ff6804c5ad2.png)

![image](https://cloud.githubusercontent.com/assets/1188186/5761661/2303abbe-9cdd-11e4-8712-ce39359a40cf.png)

**Comment by gep13** [comment]
I quite like this one:

![image](https://cloud.githubusercontent.com/assets/1271146/5763915/40591510-9ce6-11e4-9404-787bf0654287.png)

**Comment by juliankrispel** [comment]
Excellent! Looking at it on my phone I guess I would need to improve the contrast of it

**Comment by ferventcoder** [comment]
Make the C white?

**Comment by mwrock** [comment]
I really like what @juliankrispel is doing here. Even with the goal of running choco on different platforms I like the c: . My guess is that choco will largely be the package manager for Windows apps regardless from where you use it and the c: Drives home that distinction.

**Comment by juliankrispel** [comment]
Here you go 

![image](https://cloud.githubusercontent.com/assets/1188186/5774098/b33867b4-9d6a-11e4-967b-5ca1634b0084.png)

Right, my next step is to make some compositions that show how these would look in use. Before I go there I'd like to nail the colour of the wrapping. Any suggestions? Also, any further comments on what I've done so far @ferventcoder? Take your time I probably won't get to it until next week, got to do some paid work hehe :)

**Comment by juliankrispel** [comment]
also a decision on wether or not the colon behind the c is appropriate is called for. So far I count one vote for it and one against it. But ultimately I guess this should be the owners decision @ferventcoder.

**Comment by rismoney** [comment]
I was not against it.  I was inquiring.  I actually really like all the work you have done and have to express sincere kudos for your hard work and volunteering.  My hope for whatever logo that is chosen is that it represents choco to where its goodness becomes synomous with all the good people involved including you @juliankrispel.

**Comment by juliankrispel** [comment]
@rismoney very kind words much appreciated thank you!

Just so you know I didn't take any offence. Doing branding work for a couple of years really helped me learn to not be too attached to my own work. I appreciate the feedback that all of you have given, in fact I rely on it. Wether negative or positive, without feedback I'm flying blind.

I think the small logo works with or without the colon, so although I sway towards the colon, I don't think it makes or breaks the graphic. 

The thought behind the colon was that it adds a tiny bit of extra meaning to it. I liked the coincidence that the first letter of the product name is also the first windows drive letter. And a drive letter followed by a colon is significantly windows. I get a little sentimental when I see a `C:` it takes me back to launching [decent](https://www.youtube.com/watch?v=keS0Hts2LpQ) from my MSDOS on my first windows machine.

![image](https://cloud.githubusercontent.com/assets/1188186/5776037/99daeb9e-9d82-11e4-8548-e8b9111f1acc.png)

**Comment by rismoney** [comment]
Agree.

c:\>ocalatey ftw! :)

**Comment by AnneTheAgile** [comment]
@juliankrispel , I love all your renditions! Your pictures with the post "The idea is that you can represent your brand in different ways as long as you keep some similarities that make it identifiable." really seem gorgeous to me and very unified. 

I vote to keep the colon on the small ones and keep the non-colon, willy womka style on the big ones. Though traditionally I'd say small logos shouldn't "make you think", in this case I believe though it does 'stop' me a bit, it gives a terrific 'ah hah'. So maybe on the front page you could have both big/small somewhere.  

Also, later down the road if c:\ becomes obsolete/unfashionable, the colon could be dropped with ease.

**Comment by ferventcoder** [comment]
@juliankrispel can you render the last image with a colon so we can get a side by side? https://github.com/chocolatey/chocolatey/issues/640#issuecomment-70228696

**Comment by ferventcoder** [comment]
@juliankrispel color of the wrapping - The lighter color on https://chocolatey.org 
![image](https://cloud.githubusercontent.com/assets/63502/5837853/844f9238-a148-11e4-9d49-514df965d238.png)

**Comment by juliankrispel** [comment]
thanks @AnneTheAgile. Very encouraging! 

@ferventcoder first regarding the colour choice,  number one below is using the chocolatey light brown. To quickly get some variety, I headed over to [Adobe Color](https://color.adobe.com/explore) and searched for colour schemes related to chocolate. Then I picked some of them, the results are below. Personally, I think there are better ones than number 1 in there. What do you think?

![image](https://cloud.githubusercontent.com/assets/1188186/5838537/74d2a5da-a188-11e4-8d8b-bdef68c1a9e5.png)

![image](https://cloud.githubusercontent.com/assets/1188186/5838548/80a9daa4-a188-11e4-838f-bff415a0a6d1.png)

![image](https://cloud.githubusercontent.com/assets/1188186/5838577/a4374772-a188-11e4-9fac-d2490f6f3fa9.png)

**Comment by mwrock** [comment]
Awesome work! I like 8 the most.

**Comment by gep13** [comment]
Wow, these are really good!  Great work @juliankrispel Personally, I also like 8 a lot, but I keep coming back to normal 6 as well.  I really like the colours, although I appreciate they are completely different to what we have now :smile_cat:

**Comment by rismoney** [comment]
going to agree with @gep13  6 pops against the black background and the letters have a transparent magic quality.  I didn't notice this before, but I also love the near symmetry afforded by the C and the Y.
It certainly has a richness!

**Comment by juliankrispel** [comment]
Thanks guys! I think both 6 and 8 are good choices.

Also @ferventcoder  here are the two side by side 
![image](https://cloud.githubusercontent.com/assets/1188186/5870833/5424f312-a2d5-11e4-9989-224dab260420.png)

And here are some more variations on that icon-size, but with the packaging theme retained:

![image](https://cloud.githubusercontent.com/assets/1188186/5870939/3225a53a-a2d6-11e4-8cc4-02b022ed0d27.png)

**Comment by juliankrispel** [comment]
And here are the beginnings of an accompanying redesign of the website, in those two colour schemes. This is really only just kicking it off, there are so many paths to explore in that area as well. Of course as always feedback is welcome.

![image](https://cloud.githubusercontent.com/assets/1188186/5873822/dc2b5dd0-a2fa-11e4-88af-1ab132311a34.png)
![image](https://cloud.githubusercontent.com/assets/1188186/5873831/eefb6982-a2fa-11e4-8d1b-380bd874580c.png)
![image](https://cloud.githubusercontent.com/assets/1188186/5874283/0acc5392-a300-11e4-8504-76bfa148185a.png)

@ferventcoder If I'm going to far here at all let me know, also if you do want to discuss any of this outside of a github issue, feel free to ping me on skype or such, I'm julian[dot]krispel on skype

On a side note: I'm sick of the notion that mac apps always have better design, or that macs in general are much better for design. So one of my goals with this is to help reverse this trend a little.

**Comment by ferventcoder** [comment]
I missed mentioning it but I showed your designs to my wife and kids and they also preferred #8 then #6.

**Comment by ferventcoder** [comment]
We have plans for a redesign of the site - https://github.com/chocolatey/chocolatey.org/issues/149

**Comment by ferventcoder** [comment]
I'm digging `#8` with the white `Chocolatey` - I also like `#6` quite a bit. With the icon I'm a fan of no colon. 1b with white `C` is also quite interesting.

**Comment by gep13** [comment]
> With the icon I'm a fan of no colon. 1b with white C is also quite interesting.

Agreed, I like 1b because of the bevelled edge on the "wrapper" of the chocolate.  No colon gets my vote as well.

**Comment by juliankrispel** [comment]
colourscheme number `#8` it is then. And 1b with no colon and a white c! I'll make a final round up of the identity now. The goal is to have a zip file with all assets one could possibly need, on and offline. 

@ferventcoder All the better that the redoing of the website is already in motion. As you know, I'd like to contribute to that as well, so I'll continue to engage with the appropriate issue. I imagine that if you take care of the content I could just chime in with some CSS and html changes. If and when you feel comfortable working on this together, let me know :)

**Comment by ferventcoder** [comment]
@juliankrispel yes, Will get with you soon on some website changes...

**Comment by juliankrispel** [comment]
@ferventcoder awesome thanks!

**Comment by ferventcoder** [comment]
Hi @juliankrispel - checking in. I noticed that the CLA I sent has still not been signed and would like to move forward.

**Comment by juliankrispel** [comment]
Oh crap. Forgot about this. Will send tomorrow morning!

**Comment by ferventcoder** [comment]
Unfortunately I don't have the assets to work with this and Julian appears to be MIA (no email response, not sure if that means I'm falling into his spam folder or something).

So I'm attempting to recreate some of this. 

Trying to recreate the font, I'm finding Hummingbird Pro similar to the font above:

* http://marketplace.veer.com/font/Hummingbird-Bold-UMT9002141?skeywords=script%20or%20handwriting (Set the tracking to -2)

![image](https://cloud.githubusercontent.com/assets/63502/14132637/aa85de4c-f60d-11e5-89bf-a9697246d87f.png)


Here are some other interesting fonts:
* http://marketplace.veer.com/font/Hummingbird-UMT9002083?skeywords=script%20or%20handwriting
* http://marketplace.veer.com/font/Bernhard-Script-Complete-RRT0011520?skeywords=calligraphy#

**Comment by ferventcoder** [comment]
Alternative font that looks really cool is Jolly Roger:

* http://marketplace.veer.com/font/Jolly-Roger-RRT0011505?skeywords=calligraphy
![image](https://cloud.githubusercontent.com/assets/63502/14132729/9120eb80-f60e-11e5-8557-e003ea0760a8.png)

**Comment by ferventcoder** [comment]
Byron Bold is also pretty interesting

* http://marketplace.veer.com/font/Byron-RRT0010014?skeywords=calligraphy
![image](https://cloud.githubusercontent.com/assets/63502/14132750/d311d55e-f60e-11e5-9e8c-cf285094f29f.png)

**Comment by ferventcoder** [comment]
Ganache (I already love the name):

* http://marketplace.veer.com/font/Ganache-UMT9002810?skeywords=script%20or%20handwriting
![image](https://cloud.githubusercontent.com/assets/63502/14132777/178e2bce-f60f-11e5-8cdb-09b719e1d5f5.png)

**Comment by juliankrispel** [comment]
Oh, so sorry give me an hour I'll upload all the files (for some reason I
imagined I already sent you everything, I didn't?)

**Comment by gep13** [comment]
@ferventcoder I like the Jolly Roger Regular :+1:

**Comment by gep13** [comment]
@juliankrispel thanks for getting back to us about this, really appreciate it! :smile_cat:

**Comment by juliankrispel** [comment]
of course I wouldn't want all that work go to waste :)

**Comment by ferventcoder** [comment]
Not sure what happened @juliankrispel - I've sent you about 4-5 emails over the last year with no response. I should have just came back here and mentioned so on GitHub as it appears my emails didn't reach you for some reason. :/

**Comment by juliankrispel** [comment]
I am so sorry rob :( I think I remember receiving one and replying but I
was travelling and had the file somewhere else

Did I never send you that .ai file? I sort of imagine I did, but that could
just be it, my imagination

**Comment by ferventcoder** [comment]
I have the AI file but it is only has the assets feom the very first part of this discussion. Nothing past https://github.com/chocolatey/chocolatey/issues/640#issuecomment-69870283

**Comment by juliankrispel** [comment]
oh ok, I'll upload all I have this afternoon!

**Comment by juliankrispel** [comment]
I honestly don't know what happened to these other emails that you've sent
me did you send them to julian [at] goodafternoon [dot] co ?

**Comment by ferventcoder** [comment]
I was not using that email (didn't know that one) and that was likely the problem. The email we were communicating on was your yahoo one (same as listed on your github profile).

**Comment by juliankrispel** [comment]
Oh, that explains everything, sorry about that I should have added an
auto-answer there that I'm not 'really' using that one anymore :)

**Comment by peterhuene** [comment]
@juliankrispel Just saw this thread and wanted to say you're awesome for having contributed to this effort :+1:

**Comment by juliankrispel** [comment]
thanks @peterhuene I'm very excited to be part of this project again and am looking forward to seeing the design in action on chocolatey :)

**Comment by ferventcoder** [comment]
This is done. Super awesome logo...
