### ISSUE TITLE
Package autocompletion

### ISSUE THREAD

**Issue by AntoineTurmel** [chocolatey/chocolatey#645]
It would be nice to have autocompletion for package eg:
choco install firef(*press tab*)
choco install firefox

Not sure if it's possible with current cmd/PowerShell.

**Comment by dhilgarth** [comment]
PowerArgs has this feature built in: https://github.com/adamabdelhamed/PowerArgs#tab-completion

**Comment by ferventcoder** [comment]
Moved to https://github.com/chocolatey/choco/issues/412
