### ISSUE TITLE
[Enhancement] Don't assume that $env:USERPROFILE and $env:TEMP are predefined

### ISSUE THREAD

**Issue by lonniev** [chocolatey/chocolatey#647]
The install.ps1 at chocolatey.org assumes that it can safely create a temporary temp folder using Join-Path and $env:TEMP. However, that environment variable may be unset and the directory may not exist until the current user has logged into the system. (Packer uses a VM with a bash shell and the current working user when chocolatey install.ps1 is executed has yet to perform a Windows login.)

Better: either test for the existence of any chosen base directory (e.g. C:\Windows\temp) or simply create one at the root of the filesystem and delete it when finished.

**Comment by ferventcoder** [comment]
This may be a duplicate of #554

**Comment by ferventcoder** [comment]
Actually #307.

**Comment by ferventcoder** [comment]
Closing this and updating #307

**Comment by ferventcoder** [comment]
Okay, this is partially resolved with #307 - adds a cacheLocation to the config file.

**Comment by ferventcoder** [comment]
Some of this may need to carry over to chocolatey.org where the download and install script are located.

**Comment by ferventcoder** [comment]
The rest of this will be over at https://github.com/chocolatey/chocolatey.org/issues/139

**Comment by ferventcoder** [comment]
Once 0.9.8.29 is out, you should be completely good to go.
