### ISSUE TITLE
Need downloading files progress in console

### ISSUE THREAD

**Issue by ahmedmohiduet** [chocolatey/chocolatey#648]
While trying downloading jdk and mysql I feel like choco has freezed, but I then realized this may be because of huge download file sizes. Is there any way I can see each files download progresses, perhaps with some flags or something?

**Comment by gep13** [comment]
@ahmedmohiduet in both the Command Window and PowerShell Window you will get a download progress indication, as shown here:

![image](https://cloud.githubusercontent.com/assets/1271146/5592937/0479c5c0-91e3-11e4-8b39-4387ee505424.png)

![image](https://cloud.githubusercontent.com/assets/1271146/5592939/0bfa387a-91e3-11e4-9869-10ac792908eb.png)

These will disappear once the file download happens.  Anything after that is just the installation time.

Does that help?

Gary

**Comment by ahmedmohiduet** [comment]
In my case a new blank window appeared everytime  on top of these windows before they freeze

**Comment by ferventcoder** [comment]
@ahmedmohiduet can you indicate the exact command you used and what shell you are using?

Also please add `-debug` and post back the output from that as well. I'm looking for Posh version/chocolatey version/operating system version.

**Comment by ahmedmohiduet** [comment]
Hi ferventcoder! Sorry for my delay. I have actually tried it in my office pc today. But couldn't reproduce the issue. I will let know as soon as I am able to reproduce the issue again. :+1:

**Comment by ararog** [comment]
Can't see any download progressbar on Windows Server 10 Tech Preview 2.

**Comment by ferventcoder** [comment]
@ararog you should probably look at https://github.com/chocolatey/choco and particularly https://github.com/chocolatey/choco/issues/56
