### ISSUE TITLE
Install grunt and bower

### ISSUE THREAD

**Issue by LeG3nDz** [chocolatey/chocolatey#649]
HI community,

I've used Chocolatey for install nodejs (nodejs.install) and after installing grunt and bower, i can't use this.

If i test grunt -v or bower -v :

    grunt is not defined

Do you have idea ? :)

Thank you !

**Comment by gep13** [comment]
In order for this to work, you would have to do the following:

```choco install nodejs.install```

Close and re-open your Command/PowerShell window

```npm install -g grunt-cli```

```npm install -g bower```

The important thing here is the closing of the shell to get the initial npm installs to work.

Hope that helps!

Gary
