### ISSUE TITLE
Config files get overwritten on every update

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/chocolatey#650]
chocopkgup.exe.config in ChocolateyBinRoot/ChocolateyPackageUpdater gets overwritten on every update so that every time the "PackagesFolder" key changes back to default, breaking ketarin-updates.

**Comment by gep13** [comment]
@aronovgj I think that this issue would be best added here:

https://github.com/chocolatey/chocolatey-package-updater

Can you please re-create the issue there, and I will close this issue.

Thanks

**Comment by aronovgj** [comment]
I thought so too but I did what I was told:
https://groups.google.com/d/msg/chocolatey/VZIbnZTyGLU/47C5RHo_zlYJ

Am 02.01.2015 um 11:45 schrieb Gary Ewan Park:

**Comment by ferventcoder** [comment]
Actually this is a chocolatey issue - let me update the issue wording.

**Comment by gep13** [comment]
@aronovgj please accept my apologies, I was unaware of the history of this issue, and based on the wording, I believed it sounded like a ChocoPkgUp.exe issue, not a native Chocolatey one.

**Comment by aronovgj** [comment]
not a problem at all...

**Comment by ferventcoder** [comment]
This has bee moved to https://github.com/chocolatey/choco/issues/110

**Comment by ferventcoder** [comment]
Closed because move.
