### ISSUE TITLE
[Wiki] Recent change to how to article

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey#656]
Not sure how else to do this, as I can't seem to comment on the change to the wiki :cry: 

@glennsarti I am trying to understand why you made a change to the chocolatey wiki to change all the ='s to :'s.

https://github.com/chocolatey/chocolatey/wiki/How-To-Parse-PackageParameters-Argument/_compare/23d1b8c7d00d79674b1bb0ba7368f88c0ccb900d...e1a7dc741a5fbd11fd8f47d27d626a997bbb580f

Is this a personal preference, or for a valid technical reason?

This wiki article was modeled on the work that @mwrock did for the Visual Studio packages, and the method illustrated works as documented, so I don't really see a reason to change it.

Can you let me know you reasons for making this change, so I can decide whether to back out the changes or not.

Thanks

**Comment by ferventcoder** [comment]
Definitely should stay with equals if possible.

**Comment by gep13** [comment]
> Definitely should stay with equals if possible.

This is my opinion as well, but wanted to understand the thought process that @glennsarti had before rolling back.

**Comment by glennsarti** [comment]
Sure.  I changed it because the regular expression that is used expects a colon, not an equals sign  ...+):([`.... The code in the article didn't work.  Also the documentation was inconsistent.  Sometimes it used equals, and sometimes it used colon which made me really confused when I was using it.

If you'd prefer equals, I guess just need to change the regex to ...+)=([`.... and then test it.  If it works, change all the references in documentation from colon to equals.

**Comment by gep13** [comment]
Thanks for getting back to me.

I was almost convinced that I tested the code that I used before I posted it into the wiki, but sounds like there is an issue there.  Let me look at this again, and make sure it is correct.

Thanks for bringing to it our attention!

**Comment by glennsarti** [comment]
No problem.  Also, should I be allowed to make changes to wiki like that, or should I be raising an issue first?

**Comment by gep13** [comment]
Hmm, looking again, look like Matt is using a : as the separator within his packages:

https://chocolatey.org/packages/VisualStudio2013Ultimate

I must have tried to change this to = and messed up the article.

I will correct his.

**Comment by gep13** [comment]
> No problem. Also, should I be allowed to make changes to wiki like that, or should I be raising an issue first?

That would be for @ferventcoder to comment on for the official answer :smile_cat: 

In my mind, editing the wiki should be allowed, crowd sourcing documentation has a lot of merit.  However, perhaps we might want to use a Pull Request model for this, rather than allowing editing directly, to ensure the changes are actually required/desired.

**Comment by ferventcoder** [comment]
perhaps. How does on PR wiki docs?

**Comment by gep13** [comment]
> perhaps. How does on PR wiki docs?

Boo! I thought since the wiki is just a git repo under the hood that this would be possible, but looks like you have to fudge it!

http://fusiongrokker.com/post/how-you-can-contribute-to-taffy-documentation

**Comment by ferventcoder** [comment]
Can this be closed?

**Comment by glennsarti** [comment]
I'm happy for it to be closed
