### ISSUE TITLE
The CacheLocation is blank ('') if it does not exist in either the user or machine level chocolatey config

### ISSUE THREAD

**Issue by glennsarti** [chocolatey/chocolatey#657]
Symptom:
Note - This is version 0.9.8.29 but it is also present in .31
The following error messages is thrown;
```powershell
....
DEBUG: After checking the global config the value of 'cacheLocation' is ''
Write-Error : A configuration value for cacheLocation was not found
At C:\Dev\Chocolatey\chocolateyinstall\functions\Get-ConfigValue.ps1:20 char:7
+       Write-Error "A configuration value for $configValue was not found"
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
DEBUG: Switching $env:Temp to ''

Exception calling "CreateDirectory" with "1" argument(s): "Path cannot be the e
mpty string or all whitespace."
At C:\Dev\Chocolatey\chocolateyinstall\chocolatey.ps1:145 char:5
```
and package installation fails

Steps to reproduce:
1. Modify your user and machine level chocolatey.config files and remove the cacheLocation xml element
2. Try to install package.  I tested with a packageid that did not exist which made the test a little faster

Reason:
If the cacheLocation xml node is missing in both the user and machine location. Because an error is thrown the $cacheLocation is set to $null.  The subsequent If statements assume it's a string so;
($cacheLocation -ne '') evaluates as true but the following ($cacheLocation -eq '') evaluates as false

Lines 125-127 of https://github.com/chocolatey/chocolatey/blob/master/src/chocolatey.ps1

Proposed resolution:
Change Line 127 of https://github.com/chocolatey/chocolatey/blob/master/src/chocolatey.ps1 to;
if ($cacheLocation -eq '' -or $cacheLocation -eq $null) { $cacheLocation = "$nugetPath\temp"}

or you could use an explicit cast;
if ([string]$cacheLocation -eq '') { $cacheLocation = "$nugetPath\temp"}

**Comment by ferventcoder** [comment]
Does it have issues if you have `<cacheLocation></cacheLocation>` set? The intention is not for it to be removed.

**Comment by glennsarti** [comment]
If you add in the empty tag then no error is thrown.
In my case when I upgraded chocolatey from x.28 to x.30 it was missing.  However I could be experiencing a one-off error.

While this has a low probability of occuring and the workaround is fairly simple, I feel the logic error still needs attention;

* If the cacheLocation tag should **always** be in the config file, then the error 'Write-Error : A configuration value for cacheLocation was not found' should be terminal and perhaps steps how to fix it be presented to the user

or

* If it is _possible_ that  the cacheLocation tag to not exist, then the case of $cacheLocation of being $null should be handled in the code as per one of my proposals.

I realise this is a low priority issue, so I'm happy to make the changes and submit a PR for it.
Also happy to write some pester tests for it.

**Comment by ferventcoder** [comment]
No need. This will be completely unnecessary due to new codebase that
overrides this. The logic in this codebase may be a bit naive, yes.

On Thursday, January 8, 2015, Glenn <notifications@github.com> wrote:

> If you add in the empty tag then no error is thrown.
> In my case when I upgraded chocolatey from x.28 to x.30 it was missing.
> However I could be experiencing a one-off error.
>
> While this has a low probability of occuring and the workaround is fairly
> simple, I feel the logic error still needs attention;
>
>    - If the cacheLocation tag should *always* be in the config file, then
>    the error 'Write-Error : A configuration value for cacheLocation was not
>    found' should be terminal and perhaps steps how to fix it be presented to
>    the user
>
> or
>
>    - If it is *possible* that the cacheLocation tag to not exist, then
>    the case of $cacheLocation of being $null should be handled in the code as
>    per one of my proposals.
>
> I realise this is a low priority issue, so I'm happy to make the changes
> and submit a PR for it.
> Also happy to write some pester tests for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/657#issuecomment-69281884>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by glennsarti** [comment]
Fair enough.

I'll close the issue.
