### ISSUE TITLE
Exceptions raised in chocolateyInstall.ps1 are not resulting in a non-zero exit codes returned from chocolatey

### ISSUE THREAD

**Issue by mwrock** [chocolatey/chocolatey#659]
Exceptions raised in chocolateyInstall.ps1 are not resulting in a non-zero exit code because it is writing to the $chocolateyErrored variable in a different scope from where it was created.

**Comment by mwrock** [comment]
PR #658 should fix this.

**Comment by ferventcoder** [comment]
Duplicate of #568
