### ISSUE TITLE
I *want* my chocolatey install in C:\Chocolatey

### ISSUE THREAD

**Issue by masaeedu** [chocolatey/chocolatey#661]
I explicitly set the `ChocolateyInstall` env variable to `C:\Chocolatey`, and the installation went smoothly and moved `chocolateyInstall` over to that folder. Now I have to look at this every time I run **any** command:

![capture](https://cloud.githubusercontent.com/assets/3674056/5787378/0e7bf334-9dca-11e4-80c7-190485ebd63f.PNG)

Is there a way to suppress the message? It would also be great if the entire decision making tree that leads to the message being shown could be taken out; I'm not sure if that is the primary factor, but all chocolatey commands are pretty darn slow right now.

**Comment by ferventcoder** [comment]
The next upgrade is going to automatically move choco, I've just finished
testing that code. Hmm, what we could do is have you set an environment
variable that it would explicitly look for and not do the move. The message
is gone as well.

What do you think of ChocolateyKeepRootDirectoryIUnderstandThe
SecurityIssuesAndDoNotCare? Too long?  :)

How about ChocolateyAllowInsecureRootDirectory?  Create it and set it to
true.

On Friday, January 16, 2015, masaeedu <notifications@github.com> wrote:

> I explicitly set the ChocolateyInstall env variable to C:\Chocolatey, and
> the installation went smoothly and moved chocolateyInstall over to that
> folder. Now I have to look at this every time I run *any* command:
>
> [image: capture]
> <https://cloud.githubusercontent.com/assets/3674056/5787378/0e7bf334-9dca-11e4-80c7-190485ebd63f.PNG>
>
> Is there a way to suppress the message (it would also be great if the
> entire decision making tree that leads to the message being shown could be
> taken out; I'm not sure if that is the primary factor, but all chocolatey
> commands are pretty darn slow right now).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/661>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by masaeedu** [comment]
I don't have that much stuff installed. If the message is gone in the next version, I could just nuke my directory, get the latest version, then install again with the same environment vars config (which I'm assuming will land my chocolatey install in C:\Chocolatey again, sans annoying messages). That way you wouldn't have to add the one off option you're describing.

**Comment by ferventcoder** [comment]
I guess I wasn't clear. No matter what, choco will not install or upgrade
into that directory (aside from manually) unless we set up the additional
env variable.

On Friday, January 16, 2015, masaeedu <notifications@github.com> wrote:

> I don't have that much stuff installed. If the message is gone in the next
> version, I could just nuke my directory, get the latest version, then
> install again with the same environment vars config (which I'm assuming
> will land my chocolatey install in C:\Chocolatey again, sans annoying
> messages). That way you wouldn't have to add the one off option you're
> describing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/661#issuecomment-70352634>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by masaeedu** [comment]
Oh, okay. I've set up the variable you're describing manually. It might be nice to turn the non-actionable message above into a prompt that sets the variable automatically (although that might be overkill).

**Comment by masaeedu** [comment]
What I don't understand is whether this check for chocolatey being in C:\chocolatey is going to remain in the codebase on a permanent basis. If not (i.e. you're removing the message and the corresponding check), C:\Chocolatey should be treated as a normal directory, and setting `ChocolateyInstall` to C:\Chocolatey should behave equivalently to setting it to `C:\Users\Me\Documents\Bobs\Your\Uncle`. Am I misunderstanding what's going on?
