### ISSUE TITLE
Unable to install or run chocolatey when $env:PSModulePath is modified with network mapped drive

### ISSUE THREAD

**Issue by jeffchulg** [chocolatey/chocolatey#662]
Hello, I try to install Chocolatey using the command provided on your website 
iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))

Here is what I get : 

PS C:\Users\sai_db> iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
Downloading https://chocolatey.org/api/v2/package/chocolatey/ to C:\Users\sai_db\AppData\Local\Temp\chocolatey\chocInsta
ll\chocolatey.zip
Download 7Zip commandline tool
Downloading https://chocolatey.org/7za.exe to C:\Users\sai_db\AppData\Local\Temp\chocolatey\chocInstall\7za.exe
Extracting C:\Users\sai_db\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\sai_db\AppData\Local\Tem
p\chocolatey\chocInstall...

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\sai_db\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip

Extracting  _rels\.rels
Extracting  chocolatey.nuspec
Extracting  tools\chocolateyInstall.ps1
Extracting  tools\chocolateysetup.psm1
Extracting  tools\init.ps1
Extracting  tools\chocolateyInstall\chocolatey.cmd
Extracting  tools\chocolateyInstall\chocolatey.config
Extracting  tools\chocolateyInstall\chocolatey.ps1
Extracting  tools\chocolateyInstall\LICENSE.txt
Extracting  tools\chocolateyInstall\NuGet.exe
Extracting  tools\chocolateyInstall\NuGet.exe.ignore
Extracting  tools\chocolateyInstall\functions\Append-Log.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-Cygwin.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-Help.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-Install.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-InstallAll.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-InstallExtension.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-InstallIfMissing.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-List.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-NuGet.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-Pack.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-PackagesConfig.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-Push.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-Python.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-RubyGem.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-Sources.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-Uninstall.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-Update.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-Version.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-WebPI.ps1
Extracting  tools\chocolateyInstall\functions\Chocolatey-WindowsFeatures.ps1
Extracting  tools\chocolateyInstall\functions\Create-InstallLogIfNotExists.ps1
Extracting  tools\chocolateyInstall\functions\Delete-ExistingErrorLog.ps1
Extracting  tools\chocolateyInstall\functions\Generate-BinFile.ps1
Extracting  tools\chocolateyInstall\functions\Get-ChocolateyBins.ps1
Extracting  tools\chocolateyInstall\functions\Get-ConfigValue.ps1
Extracting  tools\chocolateyInstall\functions\Get-GlobalConfigValue.ps1
Extracting  tools\chocolateyInstall\functions\Get-LatestPackageVersion.ps1
Extracting  tools\chocolateyInstall\functions\Get-LongPackageVersion.ps1
Extracting  tools\chocolateyInstall\functions\Get-PackageFoldersForPackage.ps1
Extracting  tools\chocolateyInstall\functions\Get-PackageFolderVersions.ps1
Extracting  tools\chocolateyInstall\functions\Get-SourceArguments.ps1
Extracting  tools\chocolateyInstall\functions\Get-Sources.ps1
Extracting  tools\chocolateyInstall\functions\Get-UserConfigValue.ps1
Extracting  tools\chocolateyInstall\functions\Get-VersionsForComparison.ps1
Extracting  tools\chocolateyInstall\functions\Move-BadInstall.ps1
Extracting  tools\chocolateyInstall\functions\Remove-BinFile.ps1
Extracting  tools\chocolateyInstall\functions\Remove-LastInstallLog.ps1
Extracting  tools\chocolateyInstall\functions\Run-ChocolateyProcess.ps1
Extracting  tools\chocolateyInstall\functions\Run-ChocolateyPS1.ps1
Extracting  tools\chocolateyInstall\functions\Run-NuGet.ps1
Extracting  tools\chocolateyInstall\functions\Write-UserConfig.ps1
Extracting  tools\chocolateyInstall\helpers\chocolateyInstaller.psm1
Extracting  tools\chocolateyInstall\helpers\functions\Get-BinRoot.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-CheckSumValid.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-ChocolateyUnzip.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-ChocolateyWebFile.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-EnvironmentVariable.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-EnvironmentVariableNames.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-FtpFile.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-ProcessorBits.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-UACEnabled.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-VirusCheckValid.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-WebFile.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Get-WebHeaders.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyDesktopLink.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyEnvironmentVariable.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyExplorerMenuItem.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyFileAssociation.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyInstallPackage.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyPackage.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyPath.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyPinnedTaskBarItem.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyPowershellCommand.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyVsixPackage.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Install-ChocolateyZipPackage.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Set-EnvironmentVariable.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Test-ProcessAdminRights.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Uninstall-ChocolateyPackage.ps1
Extracting  tools\chocolateyInstall\helpers\functions\UnInstall-ChocolateyZipPackage.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Update-SessionEnvironment.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Write-ChocolateyFailure.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Write-ChocolateySuccess.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Write-Debug.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Write-Error.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Write-FileUpdateLog.ps1
Extracting  tools\chocolateyInstall\helpers\functions\Write-Host.ps1
Extracting  tools\chocolateyInstall\redirects\choco.exe
Extracting  tools\chocolateyInstall\redirects\choco.exe.ignore
Extracting  tools\chocolateyInstall\redirects\chocolatey.exe
Extracting  tools\chocolateyInstall\redirects\chocolatey.exe.ignore
Extracting  tools\chocolateyInstall\redirects\cinst.exe
Extracting  tools\chocolateyInstall\redirects\cinst.exe.ignore
Extracting  tools\chocolateyInstall\redirects\clist.exe
Extracting  tools\chocolateyInstall\redirects\clist.exe.ignore
Extracting  tools\chocolateyInstall\redirects\cpack.exe
Extracting  tools\chocolateyInstall\redirects\cpack.exe.ignore
Extracting  tools\chocolateyInstall\redirects\cpush.exe
Extracting  tools\chocolateyInstall\redirects\cpush.exe.ignore
Extracting  tools\chocolateyInstall\redirects\cuninst.exe
Extracting  tools\chocolateyInstall\redirects\cuninst.exe.ignore
Extracting  tools\chocolateyInstall\redirects\cup.exe
Extracting  tools\chocolateyInstall\redirects\cup.exe.ignore
Extracting  tools\chocolateyInstall\redirects\cver.exe
Extracting  tools\chocolateyInstall\redirects\cver.exe.ignore
Extracting  tools\chocolateyInstall\redirects\RefreshEnv.cmd
Extracting  tools\chocolateyInstall\tools\7za.exe
Extracting  tools\chocolateyInstall\tools\7za.exe.ignore
Extracting  tools\chocolateyInstall\tools\7za.exe.manifest
Extracting  tools\chocolateyInstall\tools\7zip.license.txt
Extracting  tools\chocolateyInstall\tools\checksum.exe
Extracting  tools\chocolateyInstall\tools\checksum.exe.ignore
Extracting  tools\chocolateyInstall\tools\checksum.license.txt
Extracting  tools\chocolateyInstall\tools\shimgen.exe
Extracting  tools\chocolateyInstall\tools\shimgen.exe.ignore
Extracting  tools\chocolateyInstall\tools\shimgen.license.txt
Extracting  package\services\metadata\core-properties\ef5de462813d47c3a6fce804c73e3efa.psmdcp
Extracting  [Content_Types].xml

Everything is Ok

Files: 119
Size:       2740748
Compressed: 1017059
Installing chocolatey on this machine
Import-Module : Cannot find drive. A drive with the name ''C' does not exist.
At C:\Users\sai_db\AppData\Local\Temp\chocolatey\chocInstall\tools\chocolateyInstall.ps1:11 char:28
+                                                         import-module <<<<  -name  $psm1File;
    + CategoryInfo          : ObjectNotFound: ('C:String) [Import-Module], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

The term 'Initialize-Chocolatey' is not recognized as the name of a cmdlet, function, script file, or operable program.
 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\sai_db\AppData\Local\Temp\chocolatey\chocInstall\tools\chocolateyInstall.ps1:14 char:22
+ Initialize-Chocolatey <<<<
    + CategoryInfo          : ObjectNotFound: (Initialize-Chocolatey:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Ensuring chocolatey commands are on the path

I don't know what I can do to make it install, I've not seen a log so...

**Comment by ferventcoder** [comment]
THere are other options for install. - Can you take a look at those as a workaround for now? https://github.com/chocolatey/chocolatey/wiki/Installation

**Comment by jeffchulg** [comment]
Hello,
@powershell method => didn't work
PowerShell Through Batch Method => didn't work 

Both showed the same message.
As I install it on database servers, Visual studio isn't installed and won't be installed.

**Comment by ferventcoder** [comment]
Download the package, unzip it (https://chocolatey.org/api/v2/packages/chocolatey/) In the tools folder is a chocolateyInstall.ps1, run it with PowerShell. If it doesn't work, you likely not met the requirements.

**Comment by ferventcoder** [comment]
I fixed the url, so you'll need to visit the github page.

**Comment by ferventcoder** [comment]
For full instructions, I added the following: https://github.com/chocolatey/chocolatey/wiki/Installation#download--powershell-method

**Comment by jeffchulg** [comment]
It doesn't work. I have the exact same message.
The problem is clearly when it tries to Import a module, as if the provided module was not the good 
one...

I use a member of the Administrators group. The execution policy is Unrestricted. I even ran it with the "right click" run as administrator to be sure.
I use powershell 2.0.

**Comment by ferventcoder** [comment]
It's looking for `$env:SystemDrive` coming back with C: and then giving you a message that Drive C doesn't exist.

**Comment by ferventcoder** [comment]
Actually this is even more interesting. It happens before that - 

```powershell
$toolsPath = (Split-Path -parent $MyInvocation.MyCommand.Definition)

# ensure module loading preference is on
$PSModuleAutoLoadingPreference = "All";

$modules = Get-ChildItem $toolsPath -Filter *.psm1
$modules | ForEach-Object {
														$psm1File = $_.FullName;
														$moduleName = $([System.IO.Path]::GetFileNameWithoutExtension($psm1File))
														remove-module $moduleName -ErrorAction SilentlyContinue;
														import-module -name  $psm1File;
													}

Initialize-Chocolatey

```

For some reason it doesn't recognize the $psm1File path.

**Comment by ferventcoder** [comment]
Here's what I want you to do. Edit that `chocolateyInstall.ps1` to be:

```powershell
$toolsPath = (Split-Path -parent $MyInvocation.MyCommand.Definition)

Write-Output "`$toolsPath = $toolsPath"
# ensure module loading preference is on
$PSModuleAutoLoadingPreference = "All";

$modules = Get-ChildItem $toolsPath -Filter *.psm1
$modules | ForEach-Object {
    $psm1File = $_.FullName;
    Write-Output "`$psm1File = $psm1File"
    $moduleName = $([System.IO.Path]::GetFileNameWithoutExtension($psm1File))
    remove-module $moduleName -ErrorAction SilentlyContinue;
    import-module -name  $psm1File;
}

Initialize-Chocolatey
```

Run that and put the results back in this ticket please.

**Comment by jeffchulg** [comment]
PS F:\JEL-DBA\Projets\Server Installation - SQL Server 2012\scripts\chocolatey.0.9.8.31\tools> .\chocolateyInstall.ps1
$toolsPath = F:\JEL-DBA\Projets\Server Installation - SQL Server 2012\scripts\chocolatey.0.9.8.31\tools
$psm1File = F:\JEL-DBA\Projets\Server Installation - SQL Server 2012\scripts\chocolatey.0.9.8.31\tools\chocolateysetup.
psm1
Import-Module : Lecteur introuvable. Il n'existe aucun lecteur nommé « 'T ».
Au niveau de F:\JEL-DBA\Projets\Server Installation - SQL Server 2012\scripts\chocolatey.0.9.8.31\tools\chocolateyInsta
ll.ps1 : 13 Caractère : 18
+     import-module <<<<  -name  $psm1File;
    + CategoryInfo          : ObjectNotFound: ('T:String) [Import-Module], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Le terme « Initialize-Chocolatey » n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou pro
gramme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est co
rrect et réessayez.
Au niveau de F:\JEL-DBA\Projets\Server Installation - SQL Server 2012\scripts\chocolatey.0.9.8.31\tools\chocolateyInsta
ll.ps1 : 16 Caractère : 22
+ Initialize-Chocolatey <<<<
    + CategoryInfo          : ObjectNotFound: (Initialize-Chocolatey:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS F:\JEL-DBA\Projets\Server Installation - SQL Server 2012\scripts\chocolatey.0.9.8.31\tools>

**Comment by jeffchulg** [comment]
For the other server I tested, 

$toolsPath = S:\testings\chocolatey.0.9.8.31\tools
$psm1File = S:\testings\chocolatey.0.9.8.31\tools\chocolateysetup.psm1

**Comment by ferventcoder** [comment]
Do you have any idea why it is searching for C?

This seems a powershell issue, not a chocolatey issue. It seems like it wants to import the module to somewhere on the C drive (which doesn't exist).

I'd also like the output of `$env:SystemDrive` from those machines.

Also, are those drives local drives or network mapped drives? You can't use network mapped drives without setting proper permissions for .Net. That is out of the context of this issue for me to explain that one - https://www.google.com/webhp?ie=UTF-8#q=.net%20permissions%20network%20share

**Comment by ferventcoder** [comment]
If it is a network mapped drive, you will need to set permissions appropriately, some helpful articles:

 * https://www.sellsbrothers.com/posts/Details/1519
* http://stackoverflow.com/questions/3718697/nant-failing-with-bad-permissions-on-build-server
* http://blogs.msdn.com/b/shawnfa/archive/2004/12/30/344554.aspx

**Comment by jeffchulg** [comment]
$env:SystemDrive sends "C:". It does exist. 

C: is not a network map. But, there are network mapped drives on those servers.

I'm out of the office now. I'll check your suggestions tomorrow.

**Comment by ferventcoder** [comment]
Sounds like first you need to fix $env:SystemDrive to the proper system drive. It should have been done based on the way the computer had the system drive moved.

**Comment by ferventcoder** [comment]
I am curious if `F:` and `S:` drives are network mapped drives. Trying to run code from there without the proper trust set up is going to cause you issues. It's possible you haven't hit those yet due to your first issue.

**Comment by jeffchulg** [comment]
Well, actually, yes, they are..
I changed the location where I start chocolateyInstall.ps1. It stil shows me the same message. One point with the T: is that the network mapped drive is mapped using credentials from an active directory...

I think I have found the problem. My environment variable $env:PSModulePath is set with references to those network mapped storages. If I set for the installation this variable to only its default value, it works.

But once I want to use choco, I get the same error as above.
I set this variable a while ago because I have PS modules that are on those drives that I want to use globally.
Would it be a solution to set prior to any run of choco and choco install a command like this but with using current user instead of "Administrateur" : 
$env:PSModulePath =  C:\Users\Administrateur\Documents\WindowsPowerShell\Modules;;;C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
?

**Comment by ferventcoder** [comment]
Hmmm, that's no bueno. I think we'll want you to jump on choco.exe as soon as we have a beta available. Until then you could set the $env:PSModulePath explicitly in chocolatey.cmd as part of starting it up. It will only affect chocolatey while it is running.

**Comment by AnneTheAgile** [comment]
@jeffchulg , so this issue is solely because on server we often use non-C: drives, right? Could you update the ticket title to indicate the issue is with the drive letter? 
AnneTheAgile, CodeTriage fan

**Comment by jeffchulg** [comment]
@AnneTheAgile Done.

**Comment by ferventcoder** [comment]
I'm not sure if this is is still affected in the c# version. If you find this is still the case, please open an issue over at https://github.com/chocolatey/choco/issues/new and reference this issue. Thanks!
