### ISSUE TITLE
System path becomes corrupted during an update

### ISSUE THREAD

**Issue by BHazel** [chocolatey/chocolatey#665]
When I run an update and sometimes an install my system path becomes corrupted.  For example, links to Windows Explorer, Notepad and other system apps are not accessible until I log back into Windows.  I am using Chocolatey 0.9.8.31 with admin privileges.

Replication:
1. Run `choco update all`.
2. Once complete open a shortcut to Windows Explorer or any program in the `%Windows%\System32` directory such as Notepad or Paint.
2a. If the above does not reproduce try installing a package.  One I just tried was `choco install pip`.

Generally, I think Chocolatey is brilliant - I usually check for a package via it before downloading official installers!

**Comment by ferventcoder** [comment]
Path persisted or local shell path?

**Comment by ferventcoder** [comment]
Do you know if these packages that are being installed/updated are using Install-ChocolateyPath?

**Comment by ferventcoder** [comment]
I could see an issue with the way it would expand registry values on update. I did some work recently to keep that from happening in other tool. I plan to bring back some of that to choco as well.

**Comment by BHazel** [comment]
Thanks for your posts and apologies for my delayed response!  I am not entirely sure - I'll look a little deeper into the packages and let you know.

**Comment by BHazel** [comment]
Sorry for the delay.  It may well be an issue with my machine specifically as the issue is not appearing consistently.  Rebooting the machine always solves the problem.  I'll keep an eye on it and report back if I notice a pattern emerging.

**Comment by ferventcoder** [comment]
I'll close for now. Feel free to open a new issue and reference this (or just comment here again) if you run into this issue again.

**Comment by BHazel** [comment]
It turns out this was caused by the system path being longer than 2047 characters and is therefore not an issue for Chocolatey.  :)

**Comment by ferventcoder** [comment]
Thanks for the follow up!
