### ISSUE TITLE
[Docs] Missing images

### ISSUE THREAD

**Issue by ComFreek** [chocolatey/chocolatey#667]
https://github.com/chocolatey/chocolatey/wiki/AutomaticPackages

Three images under *Setup*, two images under *Create an Automatic Package* and two further images under *Notes about tri-packages* are missing.

**Comment by ferventcoder** [comment]
I see those images fine?

**Comment by ComFreek** [comment]
Right, I can confirm it now. It must have been a problem with the CDN.
