### ISSUE TITLE
[Docs] Automatic packages: path to Ketarin wrong

### ISSUE THREAD

**Issue by ComFreek** [chocolatey/chocolatey#668]
The path to Ketarin listed under *Testing Ketarin/ChocoPkgUp* is wrong: `https://github.com/chocolatey/chocolatey/wiki/AutomaticPackages`
The path `C:\ProgramData\chocolateypackageupdater` doesn't exist on my machine. However´, `C:\ProgramData\chocolatey\bin\Ketarin.exe` does exist.

I am posting this issue just to be extra sure I won't change documentation in its "production environment" (the changes are not reviewed, I guess).

**Comment by ferventcoder** [comment]
Thanks.

**Comment by ferventcoder** [comment]
Will be fixing in chocolatey/choco

**Comment by ferventcoder** [comment]
Well apparently the commit didn't close this but https://github.com/chocolatey/choco/wiki/AutomaticPackages#testing-ketarinchocopkgup and https://github.com/chocolatey/choco/wiki/AutomaticPackages/_compare/5701cb8178cb7449de3c6fcc6d3f6efca03ddc09...6f6e97c164a85a556cb7fbab81b4246adde24947
