### ISSUE TITLE
Remove references to chocolately gods

### ISSUE THREAD

**Issue by ahoffmann-wi** [chocolatey/chocolatey#669]
The phrases *The chocolatey gods have answered your request!* and *Boo to the chocolatey gods!* should be removed as they do not provide meaningful information to the user. They also could prove troublesome with translation to other languages and cultures.

**Comment by BNoohi** [comment]
https://github.com/chocolatey/chocolatey/wiki/ChocolateyFAQs#what-is-with-the-chocolatey-gods-in-the-installs

Also, they don't necessarily need to be translated.

**Comment by ahoffmann-wi** [comment]
There's a FAQ about the joke, which implies many users bring it up. The FAQ
is also condescending and dismissive to the user.

It may prevent enterprise use due to the unprofessional messages being
displayed on workstations.

It has no value to the project and introduces risk.

I chuckled when I saw it the first time. I love easter eggs, but displaying
it every time a package is installed may be excessive.

I hope this is not disregarded by the maintainers, as I think chocolatey is
a great tool that has a future in endpoint management.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Write-ChocolateySuccess.ps1 ( still need to remove it from https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Write-ChocolateyFailure.ps1 )

**Comment by ferventcoder** [comment]
Note that is in the NEW repo. This repo is currently being deprecated. https://github.com/chocolatey/choco

**Comment by ahoffmann-wi** [comment]
Thank you for your response!

**Comment by ferventcoder** [comment]
This is closed now with https://github.com/chocolatey/choco/commit/eed1f5df88a94da88a930340b3226d97db5e4626
