### ISSUE TITLE
[Enhancement] Chocolatey should build a packages.config as you install

### ISSUE THREAD

**Issue by AnthonyMastrean** [chocolatey/chocolatey#67]
In regards to [bennage's][1] comments on #31, Chocolatey could build your machine's packages.config as you install or update items. This way, it could also track what was installed with other sources (ruby gems, webpi, etc).

You might figure out a way to do a one-time scan of the Chocolatey packages on the machine to get started.

 [1]: https://github.com/chocolatey/chocolatey/issues/31#issuecomment-3915151

**Comment by nemchik** [comment]
I know this is not exactly what you're going for with this request, but here is a powershell command you can run to kinda accomplish your goal

"choco install",[string]::Join(" ",(clist -l |%{$_ -replace '^(\S*)\s.*$','${1}'} | select -Skip 1 | select -first (((clist -l |%{$_ -replace '^(\S*)\s.*$','${1}'} | select -Skip 1 | measure).Count)-1))) -join " " > c:\cinst.bat

then just take the c:\cinst.bat that it generates and copy it to another machine (install chocolatey on the new machine first though!)

**Comment by aronovgj** [comment]
this accomplishes basically the same thing (if using old chocolatey the sting length in file.write() should be corrected)...

**Comment by nemchik** [comment]
@aronovgj yeah i didn't think about that, im using 0.9.9

**Comment by aronovgj** [comment]
sorry, edited it a few times. i actually meant my own script :)

**Comment by nemchik** [comment]
I suppose another good thing to consider would be this;

Chocolatey 0.9.9 stopped using version numbers in the lib folder naming, so if you run that command i posted and then delete all the subfolders from lib and then run the bat file it'll kinda "clean" the folder

**Comment by ferventcoder** [comment]
Closing here as the issue has been moved to https://github.com/chocolatey/choco/issues/357. Please continue discussion over there.
