### ISSUE TITLE
Unnecessary warnings in 0.9.9-rc4 upgrade?

### ISSUE THREAD

**Issue by ianchanning** [chocolatey/chocolatey#672]
I got the following warnings at the very end of the upgrade logs that would appear fairly serious when upgrading to chocolatey.0.9.9-rc4

```
Ensuring 'C:\ProgramData\chocolatey\lib\chocolatey' exists.
WARNING: Was not able to remove 'C:\ProgramData\chocolatey\bin\choco.exe.old'. This may cause errors.
WARNING: Was not able to rename 'C:\ProgramData\chocolatey\bin\choco.exe' to 'C:\ProgramData\chocolatey\bin\choco.exe.old'.
Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Finished installing 'chocolatey' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
The batch file cannot be found.
```

However the date modified timestamps for `choco.exe` (09 Feb 2015 10:04) and `choco.exe.old` (13 Jul 2015 19:03) appear reasonable.

I might understand the first warning `Was not able to remove 'C:\ProgramData\chocolatey\bin\choco.exe.old'` as I don't think I'd done an update before so it never existed. But the second one is more worrying.

I was running my dos prompt as Administrator and the file permissions on choco.exe.old give full permissions to Administrator.

**Comment by ferventcoder** [comment]
Wrong repository. https://github.com/chocolatey/choco

**Comment by ferventcoder** [comment]
But also, warnings are a good lead to what may later be an error. Warnings are usually information sake and may require action. Errors mean bad things.
