### ISSUE TITLE
Company misspelled in Company string of executables

### ISSUE THREAD

**Issue by rctgamer3** [chocolatey/chocolatey#673]
"RealDimensions Sofware, LLC"
should be
"RealDimensions Sof**t**ware, LLC"

**Comment by ferventcoder** [comment]
Where is this? Thanks in advance!

**Comment by rctgamer3** [comment]
It's in all of the binary .exe files. Every .exe has a metadata block. I found the executables here, although not sure where they come from:
https://github.com/chocolatey/choco/tree/master/src/chocolatey.resources/redirects

**Comment by ferventcoder** [comment]
Ah, just the shims. Sweet. Yeah I will get that fixed.

**Comment by ferventcoder** [comment]
This was handled in https://github.com/chocolatey/shimgen/issues/9
