### ISSUE TITLE
Package API

### ISSUE THREAD

**Issue by altembo** [chocolatey/chocolatey#677]
Hi,

I was wondering if there will be a kind of API to access the information from https://chocolatey.org/packages ? Is anything planned? :>

Greetz

**Comment by ferventcoder** [comment]
Wrong repository - there is already an API using OData.

**Comment by ferventcoder** [comment]
Sorry so short an answer. A question like this is better suited for the mailing list. If you want to learn more about the API, search for NuGet package metadata API.

If you still need to file an issue for enhancement, please do so on https://github.com/chocolatey/chocolatey.org

**Comment by altembo** [comment]
No problem, thanks for he fast reply ;-)
