### ISSUE TITLE
Require uninstall script for packages, or notify before install if uninstall script is there.

### ISSUE THREAD

**Issue by flippingtables** [chocolatey/chocolatey#680]
I have noticed that several packages do not have a uninstall script attached to them.

I prefer to use chocolatey as my package manager, but it loses much of its convenience if I manually have to go in and delete the packaged I have installed. Some packages don't even show up in Add/Remove Programs and I have to find the installed packages in Program Files and hope that there is a uninstall.exe there.

Would it be possible to let chocolatey notify me, before i install a package, if the package i´m about to install has a uninstall script associated with it?

OR: Force package maintainers to always add uninstall scripts to packages (this is more drastic, but I think it would benefit all users).

**Comment by ferventcoder** [comment]
Not necessary. The new choco (https://github.com/chocolatey/choco) has something called AutoUninstaller which will be able to see the program being installed and reverse the changes.

**Comment by flippingtables** [comment]
Excellent, keep up the good work :+1:
