### ISSUE TITLE
Install-ChocolateyFileAssociation take multiple extensions

### ISSUE THREAD

**Issue by philoushka** [chocolatey/chocolatey#683]
What do you think about converting the [Install-ChocolateyFileAssociation](https://github.com/chocolatey/chocolatey/blob/aa854645de9d0234d3017aad001e8f9bd8b46f2f/src/helpers/functions/Install-ChocolateyFileAssociation.ps1) method to acccept an array of extensions, rather than a single extension?

I found myself being un-DRY by [repeating the call to this method a handful of times](https://cloud.githubusercontent.com/assets/930731/6487878/8c94b2b8-c248-11e4-86ea-94677e09861c.PNG).

**Proposal**

1. Change param `[string] $extension` to `[string[]] $extension`
1. Loop within the method using `Foreach` or whatever style you prefer and perform the same logic as current.

Benefits:

1. Existing code works as-is.
1. New code can be DRY.

I'd be happy to submit a PR if you end up liking this idea.

**Comment by ferventcoder** [comment]
+1, but please submit against https://github.com/chocolatey/choco

**Comment by philoushka** [comment]
How bad/undesirable would it be to pluralize the name of the param from `$extension` or `$extensions`?

I suppose that's a breaking change in the case where someone has this param explicitly named in a call to this function.

What's the sensitivity level to a param name change?

**Comment by ferventcoder** [comment]
> How bad/undesirable would it be to pluralize the name of the param from $extension or $extensions?

>I suppose that's a breaking change in the case where someone has this param explicitly named in a call to this function.

> What's the sensitivity level to a param name change?

We can simply alias the parameter. Boom. Problem solved. :)

>I've unit tested my fix locally. Almost ready to send a PR. I'll include a unit test as per the contrib guidlines.

Please open this issue on github.com/chocolatey/choco and reference this issue. There is a ton more you need to look at with respect to contributing - see the updated guidelines at https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md - I will be a stickler on your commit messages since I spent so much time laying out exactly how I want them formatted.

**Comment by philoushka** [comment]
Thanks Rob, will do.

Can you suggest a good existing example of a unit test for PowerShell helper functions?

**Comment by philoushka** [comment]
Moved to https://github.com/chocolatey/choco/issues/161
