### ISSUE TITLE
chocolatey.org/install.ps1 should check if chocolatey is already installed, and run "choco update" if so

### ISSUE THREAD

**Issue by Ferk** [chocolatey/chocolatey#684]
A convenient way to use chocolatey is to make a 2 lines bat file where the first line just installs chocolatey (with the handy oneliner in your homepage), and the second line simply runs "choco install <LIST OF PACKAGES HERE>", like so:

    @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
    choco install qbittorrent 7zip notepadplusplus windirstat sysinternals

Then this would be a lightweight portable installer and updater for all those packages. Which is simple for people to understand, redistribute and use.

However, because the first line always downloads and install chocolatey this could cause problems (and also unnecessary bandwidth consumption). Bat files are a pain for handling conditional evaluation and check whether choco exists, and it wouldn't be straightforward anymore for the average user to complicate the script or to use powershell or any other different language.

So it would be nice if the install.ps1 that installs chocolatey for the first time was able to check first if chocolatey was already installed and working. And if so, simply call a proper "choco update".

**Comment by ferventcoder** [comment]
Please file this against https://github.com/chocolatey/chocolatey.org.
