### ISSUE TITLE
How do I reindex local packages after reinstalling chocolatey?

### ISSUE THREAD

**Issue by esamo** [chocolatey/chocolatey#685]
Hello.

THE PROBLEM
How can I make fresh Chocolatey see packages installed by previous Chocolatey? Even one by one solution would be OK, but anyway Choco could be equipped for such auto action :).

THE GENESIS
In order to solve some problems I've removed everything Chocolatey-related, excluding logs and errors, but including information about packages that are installed.

---

Regards & respect.

**Comment by gep13** [comment]
Chocolatey "knows" which packages are installed, based on what folders exist in the lib folder.  This is what is used as the "index" of installed packages.

**Comment by ferventcoder** [comment]
It should already do this. If you can please explain, we'll decide whether this is an issue or not.

**Comment by esamo** [comment]
Choco did not reindex installed packages.

---

Microsoft Windows [Wersja 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Wszelkie prawa zastrzeżone.

C:\Windows\system32>choco list -localonly
ChocolateyGUI 0.12.3
PowerShell 4.0.20141001

---

These 2 listed I've installed right after reinstalling choco. While I had at least 10 entries on previous choco. As I mentioned but maybe not clearly, during choco uninstallation I've deleted folders named as installed packages.

---

Regards & respect.

**Comment by ferventcoder** [comment]
Not completely how you installed but maybe help us understand exact steps
you took to upgrade?

On Wednesday, March 11, 2015, esamo <notifications@github.com> wrote:

> Choco did not reindex installed packages.
> ------------------------------
>
> Microsoft Windows [Wersja 6.1.7601]
> Copyright (c) 2009 Microsoft Corporation. Wszelkie prawa zastrzeżone.
>
> C:\Windows\system32>choco list -localonly
> ChocolateyGUI 0.12.3
> PowerShell 4.0.20141001
> ------------------------------
>
> These 2 listed I've installed right after reinstalling choco. While I had
> at least 10 entries on previous choco. As I mentioned but maybe not
> clearly, during choco uninstallation I've deleted folders named as
> installed packages.
> ------------------------------
>
> Regards & respect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/685#issuecomment-78208061>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by esamo** [comment]
I've processed the first script on `https://chocolatey.org` which is 

`@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin`

And before that I uninstalled `choco` as instructed here: `https://github.com/chocolatey/chocolatey/wiki/Uninstallation`, that is deleting all related files. I didn't disturb logs and errors though....

---

Regards & respect.

**Comment by ferventcoder** [comment]
You are not supposed to uninstall - that is for when you are removing
chocolatey completely. You should just upgrade as normal - as instructed
everywhere else. On uninstall you would be removing everything and thus
there is nothing to reindex.

Apologies if this is confusing - however you are the first person that has
run into this so I'm not sure if there is anything we need to change in
documentation except maybe a large warning on the uninstall page.

Unfortunately for you, you will need to put back all of your packages
manually.


On Wednesday, March 11, 2015, esamo <notifications@github.com> wrote:

> I've processed the first script on https://chocolatey.org which is
>
> @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex
> ((new-object net.webclient).DownloadString('
> https://chocolatey.org/install.ps1'))" && SET
> PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
>
> And before that I uninstalled choco as instructed here:
> https://github.com/chocolatey/chocolatey/wiki/Uninstallation, that is
> deleting all related files. I didn't disturb logs and errors though....
> ------------------------------
>
> Regards & respect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/685#issuecomment-78383321>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by esamo** [comment]
Okay. I guess since I'm the only case, no fix is needed.

Regards & respect.

**Comment by norbert6** [comment]
Just a quick idea: Have you checked if the _ChocolateyInstall_ EnvVar ist still set correctly?
A few days ago I also noticed that chocolatey was not listing any of my installed packages, because for some reason the EnvVar was changed and therefore I had a fresh, separate chocolatey installation on my hard drive... After changing back to the old location my installed packages where detected again.
