### ISSUE TITLE
Split-Path bug preventing Chocolatey to install a package

### ISSUE THREAD

**Issue by ghost** [chocolatey/chocolatey#686]
There is a bug in `Split-Path` (PS 4.0 Win7 x64), when I run:
```
powershell -noprofile -noexit -command "split-path -parent c:\lorem\ipsum.txt"
```
it outputs:
```
Folder is: C:\Documents and Settings\All Users\Desktop\
Name is: Dostips.cmd
```

Therefore, when I run `choco install <package>`, all I get is bunch of errors:
```
Join-Path : Cannot find drive. A drive with the name 'Name is' does not exist.
```

So I modified chocolatey.ps1 and everything works like a charm:
```
#$nugetChocolateyPath = (Split-Path -parent $MyInvocation.MyCommand.Definition)
$nugetChocolateyPath = [System.IO.Path]::GetDirectoryName($MyInvocation.MyCommand.Definition)
#$nugetPath = (Split-Path -Parent $nugetChocolateyPath)
$nugetPath = [System.IO.Path]::GetDirectoryName($nugetChocolateyPath)
```

**Comment by ferventcoder** [comment]
Thanks for reporting this. Unfortunately this implementation of the choco
client has been deprecated in v0.9.9+ for a C# rewrite at
https://github.com/chocolatey/choco - you can upgrade now. :)

On Friday, March 13, 2015, mtman <notifications@github.com> wrote:

> There is a bug in Split-Path (PS 4.0 Win7 x64), when I run:
>
> powershell -noprofile -noexit -command "split-path -parent c:\lorem\ipsum.txt"
>
> it outputs:
>
> Folder is: C:\Documents and Settings\All Users\Desktop\
> Name is: Dostips.cmd
>
> Therefore, when I run choco install <package>, all I get is bunch of
> errors:
>
> Join-Path : Cannot find drive. A drive with the name 'Name is' does not exist.
>
> So I modified chocolatey.ps1 and everything works like a charm:
>
> #$nugetChocolateyPath = (Split-Path -parent $MyInvocation.MyCommand.Definition)
> $nugetChocolateyPath = [System.IO.Path]::GetDirectoryName($MyInvocation.MyCommand.Definition)
> #$nugetPath = (Split-Path -Parent $nugetChocolateyPath)
> $nugetPath = [System.IO.Path]::GetDirectoryName($nugetChocolateyPath)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/686>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by mtman** [comment]
Oh, chocolatey.org/install.ps1 still points to v0.9.8.3, is it intended?

**Comment by gep13** [comment]
Yes, that is intended.  See here:

https://github.com/chocolatey/chocolatey.org/issues/162

For more information.

**Comment by mtman** [comment]
So I upgraded using my patched version and unfortunately, the issue is still relevant:

```
C:\Users\mtman>choco install windirstat
Chocolatey v0.9.9.2
Installing the following packages:
windirstat
By installing you accept licenses for the packages.

windirstat v1.1.2.20140225
 Found 'chocolateyInstall.ps1':

$packageName = 'windirstat'
$fileType = 'exe'
$url = 'http://prdownloads.sourceforge.net/windirstat/windirstat1_1_2_setup.exe'
$silentArgs = '/S'

Install-ChocolateyPackage $packageName $fileType "$silentArgs" "$url"



Do you want to run the script?
 NOTE: If you choose not to run the script, the installation will
 fail.
 Skip is an advanced option and most likely will never be wanted.

 1) yes
 2) no [Default - Press Enter]
 3) skip
yes
 Get-Item : Cannot find drive. A drive with the name 'Folder is' does not exist.
 At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:28 char:1
 + Get-Item $helpersPath\functions\*.ps1 |
 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : ObjectNotFound: (Folder is:String) [Get-Item], DriveNotFoundException
     + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.GetItemCommand
 Join-Path : Cannot find drive. A drive with the name 'Folder is' does not exist.
 At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:36 char:19
 + $extensionsPath = Join-Path "$helpersPath" '..\extensions'
 +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : ObjectNotFound: (Folder is:String) [Join-Path], DriveNotFoundException
     + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
 Test-Path : Cannot bind argument to parameter 'Path' because it is null.
 At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:37 char:13
 + if(Test-Path($extensionsPath)) {{
 +             ~~~~~~~~~~~~~~~~~
     + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
    mand
 Install-ChocolateyPackage : The term 'Install-ChocolateyPackage' is not recognized as the name of a cmdlet, function, s
 cript file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is cor
 rect and try again.
 At C:\ProgramData\chocolatey\lib\windirstat\tools\chocolateyInstall.ps1:6 char:1
 + Install-ChocolateyPackage $packageName $fileType "$silentArgs" "$url"
 + ~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : ObjectNotFound: (Install-ChocolateyPackage:String) [], CommandNotFoundException
     + FullyQualifiedErrorId : CommandNotFoundException
windirstat install not successful.
Error while running 'C:\ProgramData\chocolatey\lib\windirstat\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details.
Failures:
 - windirstat
```
It seems that `Split-Path` is used even more frequently in the new version.

**Comment by ferventcoder** [comment]
Can you do a get-command split-path and add the output to this ticket?

On Friday, March 13, 2015, mtman <notifications@github.com> wrote:

> So I upgraded using my patched version and unfortunately, the issue is
> still relevant:
>
> C:\Users\mtman>choco install windirstat
> Chocolatey v0.9.9.2
> Installing the following packages:
> windirstat
> By installing you accept licenses for the packages.
>
> windirstat v1.1.2.20140225
>  Found 'chocolateyInstall.ps1':
>
> $packageName = 'windirstat'
> $fileType = 'exe'
> $url = 'http://prdownloads.sourceforge.net/windirstat/windirstat1_1_2_setup.exe'
> $silentArgs = '/S'
>
> Install-ChocolateyPackage $packageName $fileType "$silentArgs" "$url"
>
>
>
> Do you want to run the script?
>  NOTE: If you choose not to run the script, the installation will
>  fail.
>  Skip is an advanced option and most likely will never be wanted.
>
>  1) yes
>  2) no [Default - Press Enter]
>  3) skip
> yes
>  Get-Item : Cannot find drive. A drive with the name 'Folder is' does not exist.
>  At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:28 char:1
>  + Get-Item $helpersPath\functions\*.ps1 |
>  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      + CategoryInfo          : ObjectNotFound: (Folder is:String) [Get-Item], DriveNotFoundException
>      + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.GetItemCommand
>  Join-Path : Cannot find drive. A drive with the name 'Folder is' does not exist.
>  At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:36 char:19
>  + $extensionsPath = Join-Path "$helpersPath" '..\extensions'
>  +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      + CategoryInfo          : ObjectNotFound: (Folder is:String) [Join-Path], DriveNotFoundException
>      + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
>  Test-Path : Cannot bind argument to parameter 'Path' because it is null.
>  At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:37 char:13
>  + if(Test-Path($extensionsPath)) {{
>  +             ~~~~~~~~~~~~~~~~~
>      + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
>      + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
>     mand
>  Install-ChocolateyPackage : The term 'Install-ChocolateyPackage' is not recognized as the name of a cmdlet, function, s
>  cript file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is cor
>  rect and try again.
>  At C:\ProgramData\chocolatey\lib\windirstat\tools\chocolateyInstall.ps1:6 char:1
>  + Install-ChocolateyPackage $packageName $fileType "$silentArgs" "$url"
>  + ~~~~~~~~~~~~~~~~~~~~~~~~~
>      + CategoryInfo          : ObjectNotFound: (Install-ChocolateyPackage:String) [], CommandNotFoundException
>      + FullyQualifiedErrorId : CommandNotFoundException
> windirstat install not successful.
> Error while running 'C:\ProgramData\chocolatey\lib\windirstat\tools\chocolateyInstall.ps1'.
>  See log for details.
>
> Chocolatey installed 0/1 package(s). 1 package(s) failed.
>  See the log for details.
> Failures:
>  - windirstat
>
> It seems that Split-Path is used even more frequently in the new version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/686#issuecomment-79456564>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by mtman** [comment]
You nailed it! I had a split-path.bat script in my path I had no idea about. When I run `powershell -noprofile -noexit -command "gcm split-path"`, it finds the script, but then when I repeat the command in the open console AND use autocompletion, it finds the cmdlet. Therefore, I was wrongly assuming I am using the cmdlet.

I put the script away and the problem is solved.
