### ISSUE TITLE
Puppet Install throwing errow when random vagrant host

### ISSUE THREAD

**Issue by kishore-mohan** [chocolatey/chocolatey#687]
On vagrant provision when tried to install puppet, chocolatey giving error. But when i manually restart my VM then do `cinst puppet ` its working. But system should be automatically recognize chocolatey without restart. And this same code works fine if i didn't mention any hostname.

`Vagrant.configure(2) do |config|`
 `  config.vm.guest = :windows`
 `  config.vm.provision :shell, :path => "setup_requirements.cmd"`
 `  config.vm.provision :shell, inline: "cinst puppet"`
`end`

##setup_requirements.cmd
echo 'Ensuring .NET 4.0 is installed'
@powershell -NoProfile -ExecutionPolicy Bypass -File "c:\vagrant\install_net4.ps1"

echo 'Ensuring Chocolatey is Installed'
@powershell -NoProfile -ExecutionPolicy Bypass -File "c:\vagrant\install_chocolatey.ps1"

############################
`cinst puppet -debug`

!!ATTENTION!!
The next version of Chocolatey (v0.9.9) will require -y to perform
  behaviors that change state without prompting for confirmation. Start
  using it now in your automated scripts.

  For details on the all new Chocolatey, visit http://bit.ly/new_choco
DEBUG: Running 'Get-ConfigValue' with configValue:'cacheLocation'
DEBUG: Running 'Get-UserConfigValue' with configValue:'cacheLocation'
DEBUG: After checking the user config the value of 'cacheLocation' is ''
DEBUG: Value not found in the user config file - checking the global config
DEBUG: Running 'Get-GlobalConfigValue' with configValue:'cacheLocation'
DEBUG: After checking the global config the value of 'cacheLocation' is ''
DEBUG: Running 'Append-InstallLog' with chocoInstallLog:''
DEBUG: Arguments: $command = 'install'|$force=False
|$prerelease=False|$packageNames='puppet'
|$source=''
|$version=''|$allVersions=False
|$overrideArguments=False|$InstallArguments=''
|$localonly=False|$verbosity=False|$debug=True|$quiet=False
|$name=''|$ignoreDependencies=False|$forceX86=False
|$packageParameters=''
|PowerShellVersion=4.0|OSVersion=6.3.9600.0
DEBUG: Current Security Protocol - Ssl3, Tls
DEBUG: Running 'Chocolatey-Install' for 'puppet' with source: '', version: '',
installerArguments:''
DEBUG: Running 'Chocolatey-NuGet' for puppet with source:''. Force? False
Chocolatey (v0.9.8.33) is installing 'puppet' and dependencies. By installing yo
u accept the license for 'puppet' and each dependency you are installing.
DEBUG: Installing packages to "C:\ProgramData\chocolatey\lib".
DEBUG: Running 'Run-NuGet' for puppet with source: '', version:''
DEBUG: ___ NuGet ____
DEBUG: Running 'Get-ConfigValue' with configValue:'useNuGetForSources'
DEBUG: Running 'Get-UserConfigValue' with configValue:'useNuGetForSources'
DEBUG: After checking the user config the value of 'useNuGetForSources' is ''
DEBUG: Value not found in the user config file - checking the global config
DEBUG: Running 'Get-GlobalConfigValue' with configValue:'useNuGetForSources'
DEBUG: After checking the global config the value of 'useNuGetForSources' is
'false'
DEBUG: Running 'Get-UserConfigValue' with configValue:'sources'
DEBUG: Running 'Get-GlobalConfigValue' with configValue:'sources'
DEBUG: Using global sources
DEBUG: Using '-Source "https://chocolatey.org/api/v2/;"' as the source
arguments
DEBUG: Calling 'C:\ProgramData\chocolatey\chocolateyinstall\nuget.exe' install
puppet -OutputDirectory "C:\ProgramData\chocolatey\lib" -Source
"https://chocolatey.org/api/v2/;" -NonInteractive -NoCache
DEBUG: Installing 'puppet 3.7.4'.
Successfully installed 'puppet 3.7.4'.
DEBUG: Evaluating NuGet output for line: Installing 'puppet 3.7.4'.
DEBUG: Evaluating NuGet output for line: Successfully installed 'puppet
3.7.4'.
DEBUG: NuGet installed puppet. If we are ignoring dependencies (False) then we
will clean this up.

puppet v3.7.4
DEBUG: Running 'Delete-ExistingErrorLog' for puppet
DEBUG: Looking for failure log at
'C:\Users\Administrator\AppData\Local\Temp\chocolatey\puppet\failure.log'
DEBUG: Found the failure log. Deleting it...
DEBUG: Running 'Run-ChocolateyPS1' for puppet with
packageFolder:'C:\ProgramData\chocolatey\lib\puppet.3.7.4', action: 'install'
DEBUG:   __ PowerShell install (chocolateyinstall.ps1) __
DEBUG:   Looking for chocolateyinstall.ps1 in folder
'C:\ProgramData\chocolatey\lib\puppet.3.7.4'. If chocolateyinstall.ps1 is
found, it will be run.
DEBUG: Action file is 'chocolateyinstall.ps1'
DEBUG: Running
'C:\ProgramData\chocolatey\lib\puppet.3.7.4\tools\chocolateyinstall.ps1'
DEBUG: Running 'Install-ChocolateyPackage' for puppet with
url:'http://downloads.puppetlabs.com/windows/puppet-3.7.4.msi', args: '/qn',
fileType: 'MSI', url64bit:
'http://downloads.puppetlabs.com/windows/puppet-3.7.4-x64.msi', checksum: '',
checksumType: '', checksum64: '', checksumType64: '', validExitCodes: '0'
DEBUG: Running 'Get-ChocolateyWebFile' for puppet with
url:'http://downloads.puppetlabs.com/windows/puppet-3.7.4.msi',
fileFullPath:'C:\Users\Administrator\AppData\Local\Temp\chocolatey\puppet\puppe
tInstall.MSI',
url64bit:'http://downloads.puppetlabs.com/windows/puppet-3.7.4-x64.msi',
checksum: '', checksumType: '', checksum64: '', checksumType64: ''
DEBUG: Running 'Get-ProcessorBits'
DEBUG: CPU is 64 bit
DEBUG: Setting url to
'http://downloads.puppetlabs.com/windows/puppet-3.7.4-x64.msi' and bitPackage
to 64
DEBUG: Running 'Get-WebHeaders' with
url:'http://downloads.puppetlabs.com/windows/puppet-3.7.4-x64.msi', userAgent:
'chocolatey command line'
DEBUG: Setting the UserAgent to 'chocolatey command line'
DEBUG: Request Headers:
DEBUG:   'Accept':'*/*'
DEBUG:   'User-Agent':'chocolatey command line'
DEBUG: Response Headers:
DEBUG:   'X-Frame-Options':'SAMEORIGIN'
DEBUG:   'Keep-Alive':'timeout=5, max=100'
DEBUG:   'Connection':'Keep-Alive'
DEBUG:   'Accept-Ranges':'bytes'
DEBUG:   'Content-Length':'16220160'
DEBUG:   'Content-Type':'application/x-msi'
DEBUG:   'Date':'Tue, 17 Mar 2015 07:38:38 GMT'
DEBUG:   'ETag':'"7059-f78000-50db9cf9f7cc0"'
DEBUG:   'Last-Modified':'Wed, 28 Jan 2015 17:36:27 GMT'
DEBUG:   'Server':'Apache'
DEBUG: puppet's requested file has already been downloaded. Using cached copy
at

'C:\Users\Administrator\AppData\Local\Temp\chocolatey\puppet\puppetInstall.MSI'
.
DEBUG: Checking that
'C:\Users\Administrator\AppData\Local\Temp\chocolatey\puppet\puppetInstall.MSI'
 is the size we expect it to be.
DEBUG: Verifying package provided checksum of '' for
'C:\Users\Administrator\AppData\Local\Temp\chocolatey\puppet\puppetInstall.MSI'
.
DEBUG: Running 'Get-CheckSumValid' with
file:'C:\Users\Administrator\AppData\Local\Temp\chocolatey\puppet\puppetInstall
.MSI', checksum: '', checksumType: ''
DEBUG: Running 'Install-ChocolateyInstallPackage' for puppet with
file:'C:\Users\Administrator\AppData\Local\Temp\chocolatey\puppet\puppetInstall
.MSI', args: '/qn', fileType: 'MSI', validExitCodes: '0'
Installing puppet...
DEBUG: Running 'Start-ChocolateyProcessAsAdmin' with exeToRun:'msiexec',
statements: '/i
"C:\Users\Administrator\AppData\Local\Temp\chocolatey\puppet\puppetInstall.MSI"
 /qn '
DEBUG: Elevating Permissions and running msiexec /i
"C:\Users\Administrator\AppData\Local\Temp\chocolatey\puppet\puppetInstall.MSI"
 /qn . This may take awhile, depending on the statements.
Write-Error : [ERROR] Running msiexec with /i "C:\Users\Administrator\AppData\L
ocal\Temp\chocolatey\puppet\puppetInstall.MSI" /qn  was not successful. Exit co
de was '1603'.
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Start-Chocolat
eyProcessAsAdmin.ps1:46 char:5
+     Write-Error $errorMessage
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Write-Error

Write-Error : puppet did not finish successfully. Boo to the chocolatey gods!
-----------------------
[ERROR] [ERROR] Running msiexec with /i "C:\Users\Administrator\AppData\Local\T
emp\chocolatey\puppet\puppetInstall.MSI" /qn  was not successful. Exit code was
 '1603'.
-----------------------
At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-Chocolat
eyFailure.ps1:30 char:3
+   Write-Error $errorMessage
+   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Write-Error

DEBUG: Running 'Move-BadInstall' for puppet version: '3.7.4',
packageFolder:'C:\ProgramData\chocolatey\lib\puppet.3.7.4'
DEBUG: Moving bad package 'puppet v3.7.4' to
'C:\ProgramData\chocolatey\lib-bad'.
Write-Error : Package 'puppet v3.7.4' did not install successfully: [ERROR] Run
ning msiexec with /i "C:\Users\Administrator\AppData\Local\Temp\chocolatey\pupp
et\puppetInstall.MSI" /qn  was not successful. Exit code was '1603'.
At C:\ProgramData\chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:9
0 char:17
+                 Write-Error "Package `'$installedPackageName v$installedPacka
geV ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Write-Error

DEBUG: Evaluating NuGet output for line:
Finished installing 'puppet' and dependencies - if errors not shown in console,
none detected. Check log for errors if unsure.
DEBUG: Exiting with non-zero exit code.

**Comment by ferventcoder** [comment]
Do you still get this with choco 0.9.9?

**Comment by kishore-mohan** [comment]
No iam using Chocolatey (v0.9.8.33) in my windows server 2012. Is this fixed in 0.9.9?

**Comment by ferventcoder** [comment]
@kishore-mohan that's what I'm asking :)

**Comment by ferventcoder** [comment]
or to be more clear - I don't run into this issue

**Comment by kishore-mohan** [comment]
@ferventcoder if I use the script which referred in the https://chocolatey.org/ site to install chocolatey, it is installing v9.8.33. why still this link https://chocolatey.org/install.ps1 map with 0.9.8.33.

**Comment by ferventcoder** [comment]
That's a known change - 0.9.9 was quite a large change and we wanted to give tools that use automation some time to fix their stuff - see https://github.com/chocolatey/chocolatey.org/issues/162 and https://github.com/chocolatey/chocolatey.org/issues/163

**Comment by ferventcoder** [comment]
Closing this due to age. If you are still running into this issue in the 0.9.9.x (and now 0.9.10.x), please open a new issue over at https://github.com/chocolatey/choco/issues/new. Thanks!
