### ISSUE TITLE
Can I create custom package entry for my personal use (choco as update manager for basically anything)?

### ISSUE THREAD

**Issue by esamo** [chocolatey/chocolatey#688]
I could imagine providing `choco` the URL to package and choco on `update` request would check its' existence (still same filename) or headers (modifications time etc).

If this is not currently available, doesn't seem to be a lot of work but would at least doubled `choco`'s awesomeness.

Basically there would be no problem if all packages were in choco database and maintained securely, but most of my programs are not in the database (or e.g. not installed via choco).

---

Regards & respect.

**Comment by ferventcoder** [comment]
Yes you can. See `choco new -h` in choco 0.9.9+.

And see https://github.com/chocolatey/choco/wiki/How-To-Host-Feed
