### ISSUE TITLE
When selecting not to install an update, chocolatey asks for a rollback

### ISSUE THREAD

**Issue by christianrondeau** [chocolatey/chocolatey#696]
If I decide not to continue with the uninstall by refusing to run the script, I'm expecting *not* to receive a request to rollback. Here is an example:

```bash
Do you want to run the script?
 NOTE: If you choose not to run the script, the installation will
 fail.
 Skip is an advanced option and most likely will never be wanted.

 1) yes
 2) no [Default - Press Enter]
 3) skip
no
filezilla upgrade not successful.
User cancelled powershell portion of installation for 'C:\ProgramData\chocolatey\lib\filezilla\tools\chocolateyInstall.ps1'.
 Use skip to install without run.
 Unsuccessful operation for filezilla.
  Do you want to rollback to previous version (package files only)?
 1) yes [Default - Press Enter]
 2) no
no
```

Note that the rollback message itself could also be improved :)

For more details: https://groups.google.com/forum/#!topic/chocolatey/UVncL7PxXRg

**Comment by ferventcoder** [comment]
Before you get too far down the line with these - wrong repo, log the
issues at chocolatey/choco

On Thursday, March 19, 2015, Christian Rondeau <notifications@github.com>
wrote:

> If I decide not to continue with the uninstall by refusing to run the
> script, I'm expecting *not* to receive a request to rollback. Here is an
> example:
>
> Do you want to run the script?
>  NOTE: If you choose not to run the script, the installation will
>  fail.
>  Skip is an advanced option and most likely will never be wanted.
>
>  1) yes
>  2) no [Default - Press Enter]
>  3) skip
> no
> filezilla upgrade not successful.
> User cancelled powershell portion of installation for 'C:\ProgramData\chocolatey\lib\filezilla\tools\chocolateyInstall.ps1'. Use skip to install without run. Unsuccessful operation for filezilla.  Do you want to rollback to previous version (package files only)? 1) yes [Default - Press Enter] 2) nono
>
> Note that the rollback message itself could also be improved :)
>
> For more details:
> https://groups.google.com/forum/#!topic/chocolatey/UVncL7PxXRg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/696>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by christianrondeau** [comment]
Thanks @ferventcoder - I totally missed that. Note that I initially searched for duplicates for each, not I just moved the items and I'll re-check for duplicates later, if it's not already done.

Moved to choco repo.
