### ISSUE TITLE
Aborted Packages Marked As "Installed"

### ISSUE THREAD

**Issue by DarwinCSIWindowscom** [chocolatey/chocolatey#698]
It would be nice if Chocolatey had a transctional approach to whether a package is considered installed.  Currently if I abort a package shortly after it starts - re running says it is installed.

I know I can use -Force to override - but it is a bit counter intuitive.  I assume Chocolatey is using the existence of the package folder for "installed" and that this folder is created at the start of an install.

What if a tag file like InstallCompleted.txt was added to the package folder upon an error free completion?

This simple change would allow chocolatey to have a more "transactional" approach to "installed" marking without too much change or effort.

**Comment by gep13** [comment]
@DarwinCSIWindowscom can I get you to re-create your issue here:

https://github.com/chocolatey/chocolatey/issues/698

This is where all new work will be carried out.

Thanks!

**Comment by ferventcoder** [comment]
Fixed the link.

**Comment by ferventcoder** [comment]
Closed now that it has been moved.
