### ISSUE TITLE
Install-ChocolateyPath - add to process path by default

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/chocolatey#700]
There are many times that I have to manually add to the process path the folder for a package I just installed with chocolatey in order to use it in the same process right after install. (git, boxstarter).

It would seem harmless (since it will be there on the very next process that starts) and very helpful to just always add it to the process path which would save a lot of fussing finding the relevant path, etc.

This would allow all chocolatey packages that update the path to work in the same process - with no updates to packages and no fussing in scripts :)

**Comment by ferventcoder** [comment]
Wrong repo

**Comment by ferventcoder** [comment]
Second, this has been discussed many many times. We do add it to process path by default. But due to security settings a sub process cannot affect the parent process, so when it's done running, those path changes don't make it up to the top-level path.

**Comment by ferventcoder** [comment]
> This would allow all chocolatey packages that update the path to work in the same process - with no updates to packages and no fussing in scripts :)

They already do, as long as they are in the same process
