### ISSUE TITLE
Error "false : The term 'false' is not recognized as the name of a cmdlet" for any install/upgrade

### ISSUE THREAD

**Issue by nvivo** [chocolatey/chocolatey#701]
I'm getting this error for any upgrade or install I'm running. Trying to do a "choco upgrade all" will fail every package it finds with the same error after asking to run the script.

```
Calling command ['"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command
"[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & im
port-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScr
iptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\ilspy\tools\chocolateyInstall.ps1' -installArguments '' -forceX86 $fa
lse -packageParameters '' -overrideArgs $false"']
 false : The term 'false' is not recognized as the name of a cmdlet, function, script file, or operable program. Check t
 he spelling of the name, or if a path was included, verify that the path is correct and try again.
 At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:24 char:17
 + $overrideArgs = false
 +                 ~~~~~
     + CategoryInfo          : ObjectNotFound: (false:String) [], CommandNotFoundException
     + FullyQualifiedErrorId : CommandNotFoundException
 false : The term 'false' is not recognized as the name of a cmdlet, function, script file, or operable program. Check t
 he spelling of the name, or if a path was included, verify that the path is correct and try again.
 At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:27 char:13
 + $forceX86 = false
 +             ~~~~~
     + CategoryInfo          : ObjectNotFound: (false:String) [], CommandNotFoundException
     + FullyQualifiedErrorId : CommandNotFoundException
```

Here is the full debug output for upgrading a package: https://gist.github.com/nvivo/8bcb3646e93b7b707d8e

After the rollback ilspy is not installed anymore even though chocolatey says it is upgraded.

I was getting this error with 0.9.8, then I did an upgrade to 0.9.9.3 but I'm getting the same error.
I rebooted the machine after installing 0.9.9.3.

**Comment by ferventcoder** [comment]
You are getting this with 0.9.9+?

We had this fixed but it looks like I just reintroduced with the release I
did today.

On Sunday, March 29, 2015, Natan Vivo <notifications@github.com> wrote:

> I'm getting this error for any upgrade or install I'm running. Trying to
> do a "choco upgrade all" will fail every package it finds with the same
> error after asking to run the script.
>
> Calling command ['"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command
> "[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & im
> port-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScr
> iptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\ilspy\tools\chocolateyInstall.ps1' -installArguments '' -forceX86 $fa
> lse -packageParameters '' -overrideArgs $false"']
>  false : The term 'false' is not recognized as the name of a cmdlet, function, script file, or operable program. Check t
>  he spelling of the name, or if a path was included, verify that the path is correct and try again.
>  At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:24 char:17
>  + $overrideArgs = false
>  +                 ~~~~~
>      + CategoryInfo          : ObjectNotFound: (false:String) [], CommandNotFoundException
>      + FullyQualifiedErrorId : CommandNotFoundException
>  false : The term 'false' is not recognized as the name of a cmdlet, function, script file, or operable program. Check t
>  he spelling of the name, or if a path was included, verify that the path is correct and try again.
>  At C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1:27 char:13
>  + $forceX86 = false
>  +             ~~~~~
>      + CategoryInfo          : ObjectNotFound: (false:String) [], CommandNotFoundException
>      + FullyQualifiedErrorId : CommandNotFoundException
>
> Here is the full debug output for upgrading a package:
> https://gist.github.com/nvivo/8bcb3646e93b7b707d8e
>
> After the rollback ilspy is not installed anymore even though chocolatey
> says it is upgraded.
>
> I was getting this error with 0.9.8, then I did an upgrade to 0.9.9.3 but
> I'm getting the same error.
> I rebooted the machine after installing 0.9.9.3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey/issues/701>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by lennartb-** [comment]
Same issue, can confirm it with 0.9.9.3. Exact same error stack as above.

**Comment by ferventcoder** [comment]
Fixing. Also, log issues over at chocolatey/choco repo please`

**Comment by ferventcoder** [comment]
This was also mentioned in https://github.com/chocolatey/choco/issues/216
