### ISSUE TITLE
Read-Host halts scripts rather than prompt for input

### ISSUE THREAD

**Issue by ShaneIsrael** [chocolatey/chocolatey#702]
What I have noticed happens when trying to add a Read-Host to my chocolateyInstall.ps1 is that it just stops the script on the Read-Host line and in the console displays the blinking underscore. However if you go to type, nothing shows up and you have to force exit the script.

For example, I had something like this:
$createShortcuts = Read-Host "Would you like shortcuts to be created? y/n"

This was just an added configuration step I was going to provide to the user as some people with my tool may or may not want shortcuts created. When testing that line in PowerShell it works like it should, but when running it through a script in Chocolatey it would seem output is being re-directed.

**Comment by ferventcoder** [comment]
Whoops @ShaneIsrael wrong repo. Please open at https://github.com/chocolatey/choco/issues (link to this and close this one)
