### ISSUE TITLE
refreshenv not working

### ISSUE THREAD

**Issue by ahmedmohiduet** [chocolatey/chocolatey#704]
My 'refreshenv' is not working. After I commented out @echo off at the first line of refreshenv.cmd I found this logs on my command prompt.Any ideas why?
![image](https://cloud.githubusercontent.com/assets/3110101/7237035/7fb0310c-e7ba-11e4-9940-6a12534b70f3.png)

**Comment by ferventcoder** [comment]
Please open this in https://github.com/chocolatey/choco
