### ISSUE TITLE
Unable to use windowsfeatures or other sources

### ISSUE THREAD

**Issue by matteo-mosca** [chocolatey/chocolatey#706]
I have the latest version 0.9.9.6 installed.
When trying to list packages like this:

`choco list --source windowsfeatures`

It says 0 packages found. If I try to install a package from there (like the example in the wiki) it always says the package is not found.

Same goes for other builtin sources like webpi or ruby.

Listing and installing from default feed works properly.

Is this a bug or I am missing something? I could not find any help or prerequisites on your wiki.

Thanks.

**Comment by ferventcoder** [comment]
Closing as not applicable - you already found the proper place to post the issue though
