### ISSUE TITLE
choco/#01

### ISSUE THREAD

**Issue by commonwealthlight** [chocolatey/chocolatey#707]

**Comment by gep13** [comment]
We seem to be getting a lot of these spam additions lately :-( :-1:

**Comment by ferventcoder** [comment]
Just from this one user

**Comment by gep13** [comment]
Anyway to block?

**Comment by gep13** [comment]
Actually, just went to that user page, and clicked "Report Abuse"

**Comment by ferventcoder** [comment]
I did that already and blocked the user as well, but apparently doesn't work from an organization perspective, which kind of limits it's usefulness for most folks.

**Comment by gep13** [comment]
> @ferventcoder said...
I did that already and blocked the user as well, but apparently doesn't work from an organization perspective, which kind of limits it's usefulness for most folks.

Agreed. :cry:
