### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by hifriend21** [chocolatey/chocolatey#708]
When I try to install chocolatey: 

![default](https://cloud.githubusercontent.com/assets/12772194/8090902/326a1cd8-0fb9-11e5-8130-77e497572e62.png)

**Comment by gep13** [comment]
Sorry to hear that you are having issues!

Can you please try the answer to this StackOverflow question:

http://stackoverflow.com/questions/30720496/why-is-powershell-not-recognized-when-installing-chocolatey

Gary

**Comment by gep13** [comment]
Not sure where the MySQL command would be coming into play though?!?

**Comment by hifriend21** [comment]
Tried set PATH=%PATH%;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0
But 'powershell' is not recognized...
MySQL error had dissapeared

**Comment by gep13** [comment]
@hifriend21 you will likely need to close and open the command window for the PATH change to take effect.  Did you do this?

Can you output what is currently in your PATH variable here?

**Comment by hifriend21** [comment]
Sure, I did.
I have written differently, but nothing
![default](https://cloud.githubusercontent.com/assets/12772194/8092742/aa225eba-0fc4-11e5-864b-5f990a2e09e5.png)

What's the problem may be with powershell?

**Comment by gep13** [comment]
What happens if you try just ```@powershell```

**Comment by hifriend21** [comment]
Is not recognized

**Comment by hifriend21** [comment]
Is there any other ways to install chocolatey?

**Comment by ferventcoder** [comment]
@hifriend21 do you have PowerShell installed?

**Comment by gep13** [comment]
That was going to be my next question! :-)

If you hit the Windows key, and then search for powershell, does anything come up?

**Comment by ferventcoder** [comment]
Type `where.exe powershell` after updating your path locally like you did.

If it comes up with nothing, you need to ensure you install powershell first.

**Comment by ferventcoder** [comment]
Windows 7 - it should be there by default, but you can disable the Windows Feature.

**Comment by ferventcoder** [comment]
Nevermind, scratch that. Not sure how you disable/remove it. Unless you lite the install.

**Comment by hifriend21** [comment]
Seems like I really got a lite version of Windows. Which is I can't even install the powershell.Thanks for helping, there is no other ways to get chocolatey, exept cmd?

**Comment by gep13** [comment]
> @hifriend21 said...
Which is I can't even install the powershell.Thanks for helping, there is no other ways to get chocolatey, exept cmd?

While there are other way's to do the install, none of them really matter.  Chocolatey, at the minute, has a direct dependency on PowerShell.  If you don't have that installed, then unfortunately, you won't be able to use Chocolatey.
