### ISSUE TITLE
Chocolatey installation error on Windows 10 64bit Home-PC

### ISSUE THREAD

**Issue by piltu007** [chocolatey/chocolatey#710]
I am trying to install chocolatey on my computer. But every-time installation fails.
The full cmd line error is given below..
```
C:\WINDOWS\system32>@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
Downloading https://chocolatey.org/api/v2/package/chocolatey/ to C:\Users\SUBHAJ~1\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip
Download 7Zip commandline tool
Downloading https://chocolatey.org/7za.exe to C:\Users\SUBHAJ~1\AppData\Local\Temp\chocolatey\chocInstall\7za.exe
Extracting C:\Users\SUBHAJ~1\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\SUBHAJ~1\AppData\Local\Temp\chocolatey\chocInstall...

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\SUBHAJ~1\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip

Error: Can not open file as archive

Installing chocolatey on this machine
& : The term 'C:\Users\SUBHAJ~1\AppData\Local\Temp\chocolatey\chocInstall\tools\chocolateyInstall.ps1' is not
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if
a path was included, verify that the path is correct and try again.
At line:77 char:3
+ & $chocInstallPS1
+   ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\SUBHAJ...ateyInstall.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Ensuring chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder

C:\WINDOWS\system32>choco
'choco' is not recognized as an internal or external command,
operable program or batch file.
```

I don't know why the file can't be opened as archive. And my username is Subhajit Mishra not SUBHAJ~1. When I am trying to open the archive using WinRAR, I am getting this error: **C:\Users\Subhajit Mishra\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip: The archive is either in unknown format or damaged.**  Please resolve this issue.

 Thanks.

**Comment by ferventcoder** [comment]
Wrong repository. This goes to either chocolatey/choco, or most correctly to chocolatey/chocolatey.org

**Comment by ferventcoder** [comment]
Here's the issue technically - the site was under heavy load and so things were timing out and it was returning the 404 HTML page as the zip. You will know, the zip will be about 5KB and if you rename it to .html you will see the error page html in a text editor.

However yesterday at 17:00 PM CDT I put in a new caching strategy and increased the timeout to nearly remove this from happening in the future.

**Comment by ferventcoder** [comment]
You should delete the file and give it a shot now.

**Comment by ferventcoder** [comment]
I put this over on https://github.com/chocolatey/chocolatey.org/issues/236 and I will capture all of the technical details there.
