### ISSUE TITLE
install do not work with source and version

### ISSUE THREAD

**Issue by magmax** [chocolatey/chocolatey#711]
When trying to install a fixed version from a fixed path, Chocolatey says that cannot find the package version.

Example:
```
c:\tmp\packages>chocolatey install --source=C:\tmp\packages --pre foobar --version=0.0.0.1-Release
Installing the following packages:
foobar
By installing you accept licenses for the packages.
foobar not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: "0.0.0.1-Release"
 Source(s): "C:\tmp\packages"

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - foobar
```

Same command line but removing the version:
```
c:\tmp\packages>chocolatey install --source=C:\tmp\packages --pre foobar
Installing the following packages:
foobar
By installing you accept licenses for the packages.

foobar v0.0.0.1-Release
The package foobar wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
[...]
```

And if I list the packages in that path:
```
c:\tmp\packages>chocolatey list --source=c:\tmp\packages -pre
foobar 0.0.0.1-Release
1 packages found.
```

This happens with chocolatey versions 0.9.8.33 and 0.9.9.11

**Comment by magmax** [comment]
Tracing the code I see the problems is in nuget code. Closing this issue.

**Comment by ferventcoder** [comment]
Try removing pre when you call for a specific version. Does that work?

**Comment by magmax** [comment]
Hmmm... I've tried with nssm package(https://chocolatey.org/packages/NSSM) and it worked like a charm.

So I've tried to use a non-pre version with my package, as you suggested, and... worked. May be a problem with prerelease packages? Is it already known?

**Comment by magmax** [comment]
I've found the problem and I'm not sure if it is a chocolatey problem or not.

The problem was that my packages were named "foobar-0.0.0.1-Release" instead of "foobar.0.0.0.1-Release". Just renaming them works.

I'm not sure why whey use the hyphon ('-') instead the dot ('.'), but I will check it.

**Comment by magmax** [comment]
Found. The problem was in my code.

Sorry for the noise an thank you very much!

**Comment by ferventcoder** [comment]
Thanks for the followup!

**Comment by ferventcoder** [comment]
@magmax all future requests should go over to chocolatey/choco by the way. :)
