### ISSUE TITLE
Install Write Error VirtualBox

### ISSUE THREAD

**Issue by creativeknights2012** [chocolatey/chocolatey#713]
Trying to install 'VirtualBox' on Win7 64x 

C:\Users\*****>choco install virtualbox -debug
The default install location has been changed to 'C:\ProgramData\chocolatey'.
  This install will be updated to that location in the next version. It
  is strongly suggested you move this installation to the new location
  as soon as possible to limit write access from all users. Do not forget
  to update PATH & ChocolateyInstall environment variables.
DEBUG: Running 'Append-InstallLog' with chocoInstallLog:''
DEBUG: Arguments: $command = 'install'|$force=False
|$prerelease=False|$packageNames='virtualbox'
|$source=''
|$version=''|$allVersions=False
|$overrideArguments=False|$InstallArguments=''
|$localonly=False|$verbosity=False|$debug=True|$quiet=False
|$name=''|$ignoreDependencies=False|$forceX86=False
|$packageParameters=''
|PowerShellVersion=4.0|OSVersion=6.1.7601.65536
DEBUG: Running 'Chocolatey-Install' for 'virtualbox' with source: '', version:
'', installerArguments:''
DEBUG: Running 'Chocolatey-NuGet' for virtualbox with source:''. Force? False
Chocolatey (v0.9.8.27) is installing 'virtualbox' and dependencies. By installin
g you accept the license for 'virtualbox' and each dependency you are installing
.
DEBUG: Installing packages to "C:\Chocolatey\lib".
DEBUG: Running 'Run-NuGet' for virtualbox with source: '', version:''
DEBUG: ___ NuGet ____
DEBUG: Running 'Get-ConfigValue' with configValue:'useNuGetForSources'
DEBUG: Running 'Get-UserConfigValue' with configValue:'useNuGetForSources'
DEBUG: After checking the user config the value of 'useNuGetForSources' is ''
DEBUG: Value not found in the user config file - checking the global config
DEBUG: Running 'Get-GlobalConfigValue' with configValue:'useNuGetForSources'
DEBUG: After checking the global config the value of 'useNuGetForSources' is
'false'
DEBUG: Running 'Get-UserConfigValue' with configValue:'sources'
DEBUG: Running 'Get-GlobalConfigValue' with configValue:'sources'
DEBUG: Using global sources
DEBUG: Using '-Source "https://chocolatey.org/api/v2/;"' as the source
arguments
DEBUG: Calling 'C:\Chocolatey\chocolateyInstall\nuget.exe' install virtualbox
-OutputDirectory "C:\Chocolatey\lib" -Source "https://chocolatey.org/api/v2/;"
-NonInteractive -NoCache
DEBUG: Installing 'virtualbox 5.0.8.103449'.
Successfully installed 'virtualbox 5.0.8.103449'.
DEBUG: Evaluating NuGet output for line: Installing 'virtualbox 5.0.8.103449'.
DEBUG: Evaluating NuGet output for line: Successfully installed 'virtualbox
5.0.8.103449'.
DEBUG: NuGet installed virtualbox. If we are ignoring dependencies (False) then
 we will clean this up.

virtualbox v5.0.8.103449
DEBUG: Running 'Delete-ExistingErrorLog' for virtualbox
DEBUG: Looking for failure log at
'C:\Users\*****\AppData\Local\Temp\chocolatey\virtualbox\failure.log'
DEBUG: Running 'Run-ChocolateyPS1' for virtualbox with
packageFolder:'C:\Chocolatey\lib\virtualbox.5.0.8.103449', action: 'install'
DEBUG:   __ PowerShell install (chocolateyinstall.ps1) __
DEBUG:   Looking for chocolateyinstall.ps1 in folder
'C:\Chocolatey\lib\virtualbox.5.0.8.103449'. If chocolateyinstall.ps1 is found,
 it will be run.
DEBUG: Action file is 'chocolateyInstall.ps1'
DEBUG: Running
'C:\Chocolatey\lib\virtualbox.5.0.8.103449\tools\chocolateyInstall.ps1'
DEBUG: Running 'Start-ChocolateyProcessAsAdmin' with exeToRun:'powershell',
statements: 'certutil -addstore 'TrustedPublisher'
'C:\Chocolatey\lib\virtualbox.5.0.8.103449\tools\oracle.cer''
DEBUG: Elevating Permissions and running
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile
-ExecutionPolicy unrestricted -Command "& import-module -name
'C:\Chocolatey\chocolateyInstall\helpers\chocolateyInstaller.psm1';
try{certutil -addstore 'TrustedPublisher'
'C:\Chocolatey\lib\virtualbox.5.0.8.103449\tools\oracle.cer'; start-sleep
6;}catch{write-error 'That was not sucessful';start-sleep 8;throw;}". This may
take awhile, depending on the statements.
Write-Error : [ERROR] Running C:\Windows\System32\WindowsPowerShell\v1.0\powers
hell.exe with certutil -addstore 'TrustedPublisher' 'C:\Chocolatey\lib\virtualb
ox.5.0.8.103449\tools\oracle.cer'; was not successful. Exit code was '1'.
At C:\Chocolatey\chocolateyInstall\helpers\functions\Start-ChocolateyProcessAsA
dmin.ps1:46 char:5
+     Write-Error $errorMessage
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Write-Error

DEBUG: Running 'Move-BadInstall' for virtualbox version: '5.0.8.103449',
packageFolder:'C:\Chocolatey\lib\virtualbox.5.0.8.103449'
DEBUG: Moving bad package 'virtualbox v5.0.8.103449' to
'C:\Chocolatey\lib-bad'.
Write-Error : Package 'virtualbox v5.0.8.103449' did not install successfully:
[ERROR] Running C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe with
certutil -addstore 'TrustedPublisher' 'C:\Chocolatey\lib\virtualbox.5.0.8.10344
9\tools\oracle.cer'; was not successful. Exit code was '1'.
At C:\Chocolatey\chocolateyInstall\functions\Chocolatey-NuGet.ps1:90 char:17
+                 Write-Error "Package `'$installedPackageName v$installedPacka
geV ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Write-Error

DEBUG: Evaluating NuGet output for line:
Finished installing 'virtualbox' and dependencies - if errors not shown in conso
le, none detected. Check log for errors if unsure.

**Comment by ferventcoder** [comment]
Please file a request with the maintainers. This is not the place for package issues. Only if there is an issue with Chocolatey itself. Thanks!

**Comment by creativeknights2012** [comment]
Will Do
