### ISSUE TITLE
Use different cache location

### ISSUE THREAD

**Issue by Stift** [chocolatey/chocolatey#714]
I have recently observed that chocolatey uses the same cache as nuget does (c:\users\user1\appdata\local\nuget\cache). Which sounds first like it should not be a problem, they both save files there from different feeds. As there are some packages with the same name, like `nunit` that exist on the chocolatey and on the nuget feed, this leads to some unforeseen behaviour. Depending who comes first, the second one thinks that the package was already downloaded and uses that one. The behaviour afterwards is desastrous and really took me some to figure this out. Therefore I strongly recommend to use some different path for caching the downloaded package files as the feed is also context-wise completely different.

**Comment by ferventcoder** [comment]
We shut it off completely at one point, but must have missed it during the rewrite when we moved to NuGet.Core. I'll file an issue there.

**Comment by ferventcoder** [comment]
Moved to  https://github.com/chocolatey/choco/issues/479
