### ISSUE TITLE
Can't uninstall package

### ISSUE THREAD

**Issue by nicohvi** [chocolatey/chocolatey#715]
Hi there!

Great tool, thanks for all the hard work!

I'm running into a problem when I try to uninstall the package `msqlserver2014`. This is what happens when I try to run `choco uninstall`:

![error](https://cloud.githubusercontent.com/assets/430875/11299038/9a4c8346-8f83-11e5-99fe-0c832dcd130b.png)

I'm using choco `0.9.9.11`.

**Comment by ferventcoder** [comment]
Howdy! This appears to he an issue with the package itself?

**Comment by nicohvi** [comment]
That might be it! Is there any way to `force` uninstall the package?

**Comment by ferventcoder** [comment]
yes, use `--force`. If it also fails, you can look for skip. `-n` - See `choco uninstall -h` for options.

**Comment by ferventcoder** [comment]
By the way, all future requests should go to chocolatey/choco repository. Thanks!
