### ISSUE TITLE
Proxy setting ignored for local connections

### ISSUE THREAD

**Issue by cavaliercoder** [chocolatey/chocolatey#716]
When connecting to https://chocolatey.org/api/v2/, the chocolatey client (v0.9.9.11) correctly uses the configured proxy server (configured via `choco config set proxy`). However, when connecting to nuget servers on my local LAN segment, the proxy settings are seemingly ignored and the client attempts to connect directly.

Often times a corporate proxy is still required to access a local web/NuGet server. Could you please consider making proxy bypass configurable?

The issue persists when using an IPv4 address, hostname or FQDN of a local NuGet host.

I've confirmed this issue in WireShark and Fiddler.

Running in PowerShell on Windows 10
```
Name                           Value
----                           -----
PSVersion                      5.0.10240.16384
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10240.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

**Comment by ferventcoder** [comment]
Thanks for filing this issue. However I believe you wanted to file it at https://github.com/chocolatey/choco?

**Comment by cavaliercoder** [comment]
Thanks, I'll raise it there. Apologies for missing the notice.

**Comment by ferventcoder** [comment]
No worries, I was trying to find the already created issue

**Comment by ferventcoder** [comment]
This has been raised. I believe they are the same root cause.

**Comment by ferventcoder** [comment]
Maybe not, thought it might be related to https://github.com/chocolatey/choco/issues/466, but perhaps it is https://github.com/chocolatey/choco/issues/262. 

I see you just raised https://github.com/chocolatey/choco/issues/497

**Comment by cavaliercoder** [comment]
Thanks for taking a look
