### ISSUE TITLE
Fix Chocolatey client multiple sources

### ISSUE THREAD

**Issue by maxgaulhofer** [chocolatey/chocolatey#717]
When Chocolatey is configured with multiple sources and one source is down, the next source must be used.
Its also not clear what the priority attribute does.

**Comment by ferventcoder** [comment]
Can you explain the problem a bit more? What are you seeing, what do you expect?

Priority may be explained in `choco source -h`

**Comment by ferventcoder** [comment]
Also, this is the wrong repository.

**Comment by ferventcoder** [comment]
Please file this issue at https://github.com/chocolatey/choco/issues/new
