### ISSUE TITLE
shutdown /a causes Boxstarter to report a failure

### ISSUE THREAD

**Issue by bill-long** [chocolatey/chocolatey#719]
See https://github.com/mwrock/boxstarter/issues/148.

Short version: Boxstarter checks $LASTEXITCODE, and if that value is nonzero, it gives you a big red error message saying stuff failed. When choco sends a `shutdown /a` and no shutdown is in progress, that sets $LASTEXITCODE to 1116. This causes Boxstarter to report a failure even though all packages in the Boxstarter script succeeded.

Should choco reset $LASTEXITCODE after sending the shutdown command?

**Comment by bill-long** [comment]
Ugh, wrong repo.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/610
