### ISSUE TITLE
How to manage packages with PowerShell?

### ISSUE THREAD

**Issue by rgl** [chocolatey/chocolatey#721]
How can I manage chocolatey packages from PowerShell? For example, how to list installed packages in a "PS friendly" way alike:

```powershell
List-ChocoPackage | Select-Object Name,Version | Format-Table -AutoSize
```

Or if that's not feasible, how about having the choco binary output some kind of machine-readable-output like JSON?

**Comment by ferventcoder** [comment]
This repository is deprecated. Please see https://github.com/chocolatey/choco - your question is actually better to ask in Gitter.

**Comment by ferventcoder** [comment]
Gitter is https://gitter.im/chocolatey/choco
