### ISSUE TITLE
Could not establish trust relationship for the SSL/TLS secure channel

### ISSUE THREAD

**Issue by renerchen** [chocolatey/chocolatey#725]
Because behind a proxy , so firstly I set the proxy as following：
choco config set proxy http://xxx:port
choco config set proxyUser 'xxx'
choco config set proxyPassword 'xxx'

Then I install winrar， it works！
When I install python， it has the error：
C:>choco install python --force
Chocolatey v0.10.3
Installing the following packages:
python
By installing you accept licenses for the packages.

python3 v3.5.2.20161029 (forced) [Approved]
python3 package files install completed. Performing other installation steps.
Using explicit proxy server 'http://XXX:8080'.
Attempt to get headers for https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe failed.
The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
Downloading python3 64 bit
from 'https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe'
Using explicit proxy server 'http://XXX:8080'.
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://www.python.org/ftp/python/3.5.2/python-3.5.2-amd64.exe'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of python3 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
See log for details.

python v3.5.2.20161029 (forced) [Approved]
python package files install completed. Performing other installation steps.
The install of python was successful.
Software install location not explicitly set, could be in package or
default install location if installer.

Chocolatey installed 1/2 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures

python3 (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
See log for details.
How to solve it with powershell commads.

**Comment by ferventcoder** [comment]
@renerchen when you went to file the issue, did you happen to notice that the template that showed up in the text box said this repo is deprected and issues should be filed somewhere else (it had a link)? I'm curious, because we've had other people also do this and I want to understand if the messaging doesn't show up.

**Comment by ferventcoder** [comment]
Here is the issue - you need to upgrade .NET framework to 4.5 so Chocolatey can auto add TLS 1.1 and 1.2. There are many sites that just will not work without at least TLS 1.1 and that is not in .NET Framework 4.0, only in 4.5+. 

Then you should no longer see that message. HTH.

If it does not, please head over to https://github.com/chocolatey/choco/issues/new and continue this discussion. Thanks!
