### ISSUE TITLE
When I installed BAZEL, there was such a problem,

### ISSUE THREAD

**Issue by tiantianwei** [chocolatey/chocolatey#726]
When I installed BAZEL, there was such a problem, how to solve

The term 'convertfrom-json' is not recognized as the name of a cmdlet

**Comment by tiantianwei** [comment]
The specific mistake is this:
ERROR: The term 'convertfrom-json' is not recognized as the name of a cmdlet,
Nction, script file, or operable program. Check the spelling of the name, or
A path was included, verify that the path is correct and try again.
The install of bazel was NOT successful

**Comment by ferventcoder** [comment]
@tiantianwei When you created this issue, it appears you did not read the following:

> THIS REPOSITORY IS DEPRECATED. DO NOT CREATE AN ISSUE HERE.
> You are looking for https://github.com/chocolatey/choco instead. Thanks!

Note that it is still in your issue comments. Please advise on how we can make that clearer?

**Comment by tiantianwei** [comment]
Are you saying that BAZEL package has a problem, or a CHOCOLATEY packet has a problem, should not BAZEL package, because I tried the 0.4.3 version, it had the same problem, but if the CHOCOLATEY package, you are maintenance staff

**Comment by LaiTianWei** [comment]
@ferventcoder 
Are you saying that BAZEL package has a problem, or a CHOCOLATEY packet has a problem, should not BAZEL package, because I tried the 0.4.3 version, it had the same problem, but if the CHOCOLATEY package, you are maintenance staff

**Comment by tiantianwei** [comment]
@ferventcoder 
I am a Chinese, you can read Chinese

**Comment by tiantianwei** [comment]
I am a Chinese, can you read Chinese? @ferventcoder

**Comment by LaiTianWei** [comment]
@ferventcoder 
I am a Chinese, English is not very good, can you read Chinese?

**Comment by ferventcoder** [comment]
@tiantianwei I can not read Chinese. :D 

I am not a maintainer of the Bazel package on the community repository. You will want to follow up with the folks that are. At https://chocolatey.org/packages/bazel

![image](https://cloud.githubusercontent.com/assets/63502/23558622/ee329bc0-fff9-11e6-9ea3-b2362ae13288.png)


When you do followup, please tell them that they are using 'convertfrom-json', which is not available in PowerShell v2. HTH

**Comment by LaiTianWei** [comment]
@ferventcoder 
Well, thank you very much.
