### ISSUE TITLE
install in Windows turn wrong

### ISSUE THREAD

**Issue by Laxse** [chocolatey/chocolatey#728]
#Set-ExecutionPolicy AllSigned; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

when i install it in powershell,error message is that about Version mismatch .

I take this path AppData\Local\Temp\chocolatey,there are 7za.exe and chocolatey.zip,I cannot run the 7za.exe. So I delete the 7za.exe and it works.

**Comment by ferventcoder** [comment]
@laxselocke please file an issue at https://github.com/chocolatey/choco/issues/new. Thanks!
